### ISSUE TITLE
error happens when receive 'bytes' type data

### ISSUE THREAD

**Issue by wangcray** [jasonrbriggs/stomp.py#107]
I am using stomp.py to communicate with rabbitMQ.
When I serialize my data with JSON before send it, stomp.py works well.
But when I want to send bytes type data,  there is something wrong. 

SEND code:
```
# bytes in range(-128,128)
data = b'\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x7f'
...
c.send('/topic/test',data)
```

send() works fine. Through the RabbitMQ web management plugin, I can see the data in the queue which binds to topic 'test' . When I use **nc** tool and subcribe the topic manually, I can get the data too.
But with stomp.py, an exception happens.

RECEIVE code is as below:
```
class ProcessListener(stomp.ConnectionListener):
    def on_error(self,headers,message):
        print('received an error "%s"' % message)
    def on_message(self,headers,message):
        print(message)
...
c.set_listener('',ProcessListener())
...
c.subscribe(topic,id=1,headers=Headers)
```
Exception infomation is as below:
```
Exception in thread StompReceiverThread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/stomp/transport.py", line 310, in __receiver_loop
    f.body = decode(f.body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/stomp/backward3.py", line 25, in decode
    return byte_data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
It seems it's about codec but I know little about it. Could you please help me to figure it out?

**Comment by estadtherr** [comment]
I'm not sure about RabbitMQ, but ActiveMQ requires that the `content-length` header be specified for binary data. This is a reasonable expectation, since otherwise the STOMP receiver implementation could assume the first NULL byte is the end of text, which would throw off the socket stream, or try to decode the message body as a string, which is what seems to be the case in your traceback.

See the description of that header in the STOMP specification: https://stomp.github.io/stomp-specification-1.2.html#Header_content-length

**Comment by wangcray** [comment]
Thank you for your comment @estadtherr 
Really SORRY for being so late to reply for some reasons.
I come back to this function, and have tried to set `content-length`. But it failed too. It's not about length.
I tried to set `content_type` to `application/octet-stream`. It fails again.

I think it's all about encode/decode.
Now I use `base64.b64encode` to deal with the 256 bytes binary string(0x00~0xFF) .
It works.

**Comment by nikhil578** [comment]
Reopening this again. 
The problem happens with Python 3 where native string is unicode. If the publisher sends out a pickled object, the consumer is expected to get a byte-like object to unpickle. 

Publisher
------------
conn.send('/topic/test',  pickle.dumps(<some_obj>))


Consumer
-------------
The consumer should receive a bytes-like object to unpickle, but it gets a unicode string. 


Setting up content-length or content_type to application/octet-stream doesn't work.
