### ISSUE TITLE
Unable to reconnect after disconnect handled

### ISSUE THREAD

**Issue by mindscratch** [jasonrbriggs/stomp.py#114]
Using stomp.py 4.1.11 with STOMP 1.2 and ActiveMQ.

I have a listener:

```
class MyListener(stomp.ConnectionListener):
  def __init__(self, conn):
    self.conn = conn

  def on_disconnected(self):
    self.conn.start()
    self.conn.connect(None, None, wait=True)
    self.conn.subscribe("/queue/test", "foo-1", "client-individual")

conn = stomp.Connection12([('localhost', 61613)], reconnect_sleep_initial=2, reconnect_attempts_max=15)
conn.set_listener('', MyListener(conn))
self.conn.start()
self.conn.connect(None, None, wait=True)
self.conn.subscribe("/queue/test", "foo-1", "client-individual")

while True:
  time.sleep(1)
```

It starts up, connects and subscribes to "/queue/test". I then stop ActiveMQ, and start it again. A bunch of connection attempts are logged and then I see the messages:
```
Attempting connection...
Established connection...
Starting receiver loop....
Sending frame cmd='STOMP'....
Received frame: 'CONNECTED'....
Sending frame cmd='SUBSCRIBE'....
Receiver loop ended
```

I'm unsure as to why the receiver loop ends. At that point the subscriber no longer receives messages.

**Comment by mindscratch** [comment]
To get this working, I created a class that has a reference to the client something like this:
```
class ConnHandler(object):
    def __init__(self, conn, condition):
        self.conn = conn
        self.condition = condition

    def run(self):
        while self.running:
            with self.condition:
                self.condition.wait()
                if self.running:
                    self.client.stop()
                    self.client.start()
                    self.client.connect(None, None, wait=True)
                    self.client.subscribe("/queue/test", "foo", "client-individual")
```

I create the handler and start it with a thread, `threading.Thread(target=handler.run).start()`.

My "listener" now has a reference to the `threading.Condition`, when `on_disconnected` is called, it does `condition.notify()` which notifies my handler to stop, and reconnect.

**Comment by jasonrbriggs** [comment]
Are you sure the stop+reconnect is required?  Last time I needed something like this (which admittedly wasn't recently, so memory a bit hazy), I added a connection listener to the connection (before actually connecting), and called subscribe inside the on_connect -- so that on disconnect/reconnect it should then re-subscribe accordingly...

**Comment by mindscratch** [comment]
@jasonrbriggs i believe you're approach would also work, thanks for the suggestion.

**Comment by oscarmartinezrubi** [comment]
Hi guys,

I am having an issue with the on_disconnected() and I get the feeling it is similar to the issue described here by @mindscratch.

When I am disconnected and I try to reconnect on the on_disconnected method I end up with a duplicated connection and shortly after I get a "Receiver loop ended" from which point I stop receiving messages.

@mindscratch , can you share the entire code to solve this? What is self.client? What is the condition?

Thanks!
