### ISSUE TITLE
on_message not being invoked for a long running process, but messages being dequeued

### ISSUE THREAD

**Issue by abnth** [jasonrbriggs/stomp.py#121]
Hi

I have a long running process that subscribes to the queue once and then keeps listening to it.

The problem is: if there is nothing pushed to the queue for a long time(~12 hours in my case), the connection still remains active(I can see it in the ActiveMQ web console) but when I start pushing data to the queue again(after 12 hours(say)), on_message does not get invoked.

However, the ActiveMQ web console shows that messages are being dequeued.

 I have to kill the process and start it again and everything works just fine.

**Comment by jasonrbriggs** [comment]
Does it ever happen less than 12 hours?  I don't have a test server at the moment (other than various VirtualBox images), so nothing I can leave running for more than a few hours.

**Comment by chankitgoyal** [comment]
> Hi
> 
> I have a long running process that subscribes to the queue once and then keeps listening to it.
> 
> The problem is: if there is nothing pushed to the queue for a long time(~12 hours in my case), the connection still remains active(I can see it in the ActiveMQ web console) but when I start pushing data to the queue again(after 12 hours(say)), on_message does not get invoked.
> 
> However, the ActiveMQ web console shows that messages are being dequeued.
> 
> I have to kill the process and start it again and everything works just fine.

I'm facing same issue in one of my script. Can you please answer if you have fixed this.

**Comment by DAAworld** [comment]
> 
How did you solve this problem?

**Comment by DAAworld** [comment]
> > Hi
> > I have a long running process that subscribes to the queue once and then keeps listening to it.
> > The problem is: if there is nothing pushed to the queue for a long time(~12 hours in my case), the connection still remains active(I can see it in the ActiveMQ web console) but when I start pushing data to the queue again(after 12 hours(say)), on_message does not get invoked.
> > However, the ActiveMQ web console shows that messages are being dequeued.
> > I have to kill the process and start it again and everything works just fine.
> 
> I'm facing same issue in one of my script. Can you please answer if you have fixed this.


How did you solve this problem?
