### ISSUE TITLE
activemq-cpp client cannot receive messages

### ISSUE THREAD

**Issue by duanmuweiyu** [jasonrbriggs/stomp.py#122]
before, i use python 2.7 + stomp 3.1.3 to send message to activemq, and client based on activemq-cpp can receive message from activemq.but now, when i use python 3.5 + stomp 4.1.11 to do this again, the client received empty messages. somehow it looks like the client discard the message. i use the sample(https://github.com/jasonrbriggs/stomp.py/wiki/Simple-Example) and same phenomenon, so anyone can help me whit this?
PS： activemq-cpp version: activemq-cpp-library-3.9.3, it has a sample example

**Comment by jasonrbriggs** [comment]
So you're saying if you run the simple example pointing at activemq you get an empty response as well?

i.e. you get the following?

```
$ python simple.py hello world
received a message ""
```

**Comment by duanmuweiyu** [comment]
i mean when i use python--send message --> apache activemq  --  receive message -> activemq-cpp(a cpp version of client), then the activemq-cpp client report empty message.

**Comment by jasonrbriggs** [comment]
Sorry, but I don't believe it's a stomp.py problem.  I've tested sending messages between stomp.py -> activemq -> stomp.erl and that works fine.  Sounds more like an activemq-cpp issue to me.

**Comment by duanmuweiyu** [comment]
when i use python2.7 and  stomp 3.1.3, activemq-cpp client can receive message. Maybe it's python's problem or activemq-cpp's. Hope someone who meet s this kind of problem can avoid this by using python2.7.
