### ISSUE TITLE
Error on stomp.py install

### ISSUE THREAD

**Issue by donaghhorgan** [jasonrbriggs/stomp.py#132]
Hi, I just installed `stomp.py` on Ubuntu 16.04 using pip:

```
sudo pip install stomp.py
```

When I run `stomp` from a terminal, I get this error:

```
$ stomp --help
bash: /usr/local/bin/stomp: /Users/jasonbriggs/.python/python3.5.2/bin/python: bad interpreter: No such file or directory
```

**Comment by donaghhorgan** [comment]
It seems that the shebang line in `/usr/local/bin/stomp` is bad:

    #!/Users/jasonbriggs/.python/python3.5.2/bin/python

Changing it to this fixes the problem:

    #!/usr/bin/env python

**Comment by jasonrbriggs** [comment]
Can you see if version 4.1.15 is any better? While the egg and wheel files look like they don't have a local reference to the py version any more it looks like something (distutils or setup tools) is still replacing:

```
#! /usr/bin/env python
```

with...

```
#!python
```
...in the script. But that seems to work for me.
