### ISSUE TITLE
Listener loses messages

### ISSUE THREAD

**Issue by jacopoprendin** [jasonrbriggs/stomp.py#137]
I wrote a simple echo test

`
    import time
    import sys

    import stomp

    class MyListener(stomp.ConnectionListener):

        def on_error(self,headers,message):
            print('errore '+message)

        def on_message(self,header,message):
            print(message)

    #--- MAIN
    conn = stomp.Connection()
    conn.set_listener('', MyListener())
    conn.start()
    conn.connect('admin','admin',wait=True)
    conn.subscribe(destination='/queue/test',id=1,ack='client')

    while True:
        time.sleep(60)

    conn.disconnect()
`

Using a custom message sender or command-line client, it didn't print every odd message. So, first is printed, second no; third is printed, fourth no.
I am using Apache Activemq

**Comment by jasonrbriggs** [comment]
Have you only got one client connected to /queue/test?  Because the only way that happens is if more than one client connects to the same destination.
