### ISSUE TITLE
subscribe and listen

### ISSUE THREAD

**Issue by bharatjiitd** [jasonrbriggs/stomp.py#138]
Currently the listeners are set on the Connection method, there should be a provision for setting the listener at destination level for example see below. The advantage is that clients don't have to do the filtering.

conn.subscribe_and_listen(destination='/queue/test', id=1, ack='auto', MyListener())
conn.subscribe_and_listen(destination='/queue/test_another', id=1, ack='auto', MyAnotherListener())

I introduced subscribe_and_listen method to Protocol classes. Thoughts?

`diff --git a/stomp/protocol.py b/stomp/protocol.py
index 2812131..f38e873 100644
--- a/stomp/protocol.py
+++ b/stomp/protocol.py
@@ -24,6 +24,7 @@ class Protocol10(ConnectionListener):
         self.auto_content_length = auto_content_length
         transport.set_listener('protocol-listener', self)
         self.version = '1.0'
+        self.id_dest_map = {}
 
     def send_frame(self, cmd, headers=None, body=''):
         """
@@ -177,6 +178,13 @@ class Protocol10(ConnectionListener):
         headers[HDR_ACK] = ack
         self.send_frame(CMD_SUBSCRIBE, headers)
 
+    def subscribe_and_listen(self, destination, id=None, ack='auto', headers=None, listener=None, **keyword_headers):
+        self.subscribe(destination, id, ack, headers, keyword_headers) 
+        if listener:
+            self.id_dest_map[id] = destination
+            self.transport.set_listener(destination, listener)
+
+
     def unsubscribe(self, destination=None, id=None, headers=None, **keyword_headers):
         """
         Unsubscribe from a destination by either id or the destination name.
@@ -190,9 +198,12 @@ class Protocol10(ConnectionListener):
         headers = utils.merge_headers([headers, keyword_headers])
         if id:
             headers[HDR_ID] = id
+            dest = self.id_dest_map[id]
         if destination:
             headers[HDR_DESTINATION] = destination
-        self.send_frame(CMD_UNSUBSCRIBE, headers)
+        self.send_frame(CMD_UNSUBSCRIBE, headers)                                    
+        self.transport.remove_listener(dest or destination)
+
 
 
 class Protocol11(HeartbeatListener, ConnectionListener):
@@ -211,6 +222,7 @@ class Protocol11(HeartbeatListener, ConnectionListener):
         self.auto_content_length = auto_content_length
         transport.set_listener('protocol-listener', self)
         self.version = '1.1'
+        self.id_dest_map = {}
 
     def _escape_headers(self, headers):
         """
@@ -378,6 +390,9 @@ class Protocol11(HeartbeatListener, ConnectionListener):
         if self.auto_content_length and body and HDR_CONTENT_LENGTH not in headers:
             headers[HDR_CONTENT_LENGTH] = len(body)
         self.send_frame(CMD_SEND, headers, body)
+        self.id_dest_map[id] = destination
+        self.transport.set_listener(destination, listener)
+
 
     def subscribe(self, destination, id, ack='auto', headers=None, **keyword_headers):
         """
@@ -397,6 +412,12 @@ class Protocol11(HeartbeatListener, ConnectionListener):
         headers[HDR_ACK] = ack
         self.send_frame(CMD_SUBSCRIBE, headers)
 
+    def subscribe_and_listen(self, destination, id=None, ack='auto', headers=None, listener=None, **keyword_headers):
+        self.subscribe(destination, id, ack, headers, keyword_headers) 
+        if listener:
+            self.id_dest_map[id] = destination
+            self.transport.set_listener(destination, listener)            
+
     def unsubscribe(self, id, headers=None, **keyword_headers):
         """
         Unsubscribe from a destination by its unique identifier
@@ -409,7 +430,9 @@ class Protocol11(HeartbeatListener, ConnectionListener):
         headers = utils.merge_headers([headers, keyword_headers])
         headers[HDR_ID] = id
         self.send_frame(CMD_UNSUBSCRIBE, headers)
-
+        dest = self.id_dest_map[id]
+        if dest:
+            self.transport.remove_listener(dest)
 
 class Protocol12(Protocol11):
     """
diff --git a/stomp/transport.py b/stomp/transport.py
index 757fd6a..2fdf5b9 100644
--- a/stomp/transport.py
+++ b/stomp/transport.py
@@ -207,6 +207,14 @@ class BaseTransport(stomp.listener.Publisher):
         elif frame_type == 'disconnected':
             self.set_connected(False)
 
+        elif frame_type == 'message':
+            dest = headers['destination']
+            dest_listener = self.listeners[dest]
+            if dest_listener:
+                notify_func = getattr(listener, 'on_%s' % frame_type, None)
+                notify_func(headers, body)
+                return (headers, body)
+
         for listener in self.listeners.values():
             if not listener:
                 continue`

**Comment by jasonrbriggs** [comment]
Good idea, but the above isn't really reviewable.
