### ISSUE TITLE
Name of queue too long, in param destination, of subscribe() method

### ISSUE THREAD

**Issue by mago75** [jasonrbriggs/stomp.py#139]
Hi!

I have a problem with destination param, in subscribe() method, if the string of destination is greater than 50 characters. But I don't have the same problem, if destination param is in send() method.  

Please if you can check this. 

Thank you, and many greetings.

**Comment by jasonrbriggs** [comment]
Might be something to do with whatever message server you're using, because this isn't an issue with stomp.py.  Have double-checked with both apache-apollo and rabbitmq and fine with those.

**Comment by mago75** [comment]
I tested this, with Active MQ, and it doesn't work... The same example, wrote in Node.js and Java, works fine. But I'll check with apache-apollo. Thanks!
