### ISSUE TITLE
Small heatbeat receive grace coefficient in stomp/listener.py

### ISSUE THREAD

**Issue by BatraevEM** [jasonrbriggs/stomp.py#141]
Small coefficient in stomp/listener.py.
```python
# receive gets an additional grace of 50%
self.receive_sleep = (self.heartbeats[1] / 1000) * 1.5
```

With this coefficient, I have 3 of 4 heartbeat timeout errors when receiving individual communications.
an example in my logs with 'heart-beat': '5000,5000':

2017-01-26 10:41:27,722 INFO:Sending frame: 'heartbeat', headers={}
2017-01-26 10:41:29,416 INFO:Received frame: 'heartbeat', headers={}, len(body)=0
2017-01-26 10:41:32,723 INFO:Sending frame: 'heartbeat', headers={}
2017-01-26 10:41:34,417 INFO:Received frame: 'heartbeat', headers={}, len(body)=0
**2017-01-26 10:41:36,618** INFO:Received frame: 'MESSAGE', headers={'breadcrumbId': 'ID-solr-40216-1485338689218-0-232889', 'content-length': '368', 'expires': '0', 'mqAddressHandler': 'phnHandler', 'mqAddressArea': 'lVolga', 'timestamp': '1485416496614', 'destination': '/queue/lVolga.phnHandler', 'persistent': 'true', 'priority': '4', 'message-id': 'ID:solr-45210-1485339934237-1:12:1:1:1', 'subscription': '8477370259583884440'}, len(body)=368
2017-01-26 10:41:36,618 INFO:Sending frame: 'ACK', headers={'message-id': 'ID\\csolr-45210-1485339934237-1\\c12\\c1\\c1\\c1', 'subscription': '8477370259583884440'}
2017-01-26 10:41:41,623 INFO:Sending frame: 'heartbeat', headers={}
**2017-01-26 10:41:44,121** WARNING:Heartbeat timeout: **diff_receive=7.50261998177**, time=1485416504.12, lastrec=1485416496.62
2017-01-26 10:41:44,121 WARNING:Restart connection on heartbeat timeout

a coefficient of 2.1 but has no problem.

**Comment by jasonrbriggs** [comment]
Are you sure it's not the processing time for your message handler?  stomp.py doesn't use asynchronous event handling, so any lengthy message processing would then impact further message receipts.

**Comment by BatraevEM** [comment]
In this case, simply increasing the timeout, would solve the issues. But the problem appears for all values of heartbeat settings, even very high, more than 10 seconds. While the handler in the worst conditions of work of less than 2 seconds. A simple increase in the coefficient to 2.1 solves all problems. Perhaps the problem is on the side of the ActiveMQ, I do not have access to it. For myself, I decided the problem of increasing the coefficient. Issue can be closed.
