### ISSUE TITLE
Stomp issue on Linux

### ISSUE THREAD

**Issue by Sheelarkamath** [jasonrbriggs/stomp.py#142]
stompClient.connect({}, function (frame) {
        console.log('Connected : ' + frame);
         stompClient.subscribe('/topic/requestId/', function (data) {
              requestId = getRequestId(data.body);
                         stompClient.subscribe('/topic/progress/' + requestId, function (data) {
                             progressHandler(data.body,requestId);
                         });
   
                });
          });

I have this piece of code which works perfectly on the Mac but when deployed to Linux the request Id does not come back and the " /topic/progress/' + requestId " does not executes for the very FIRST TIME call. It works perfectly for the subsequent calls.  Any help would be appreciated.

**Comment by jasonrbriggs** [comment]
Looks like javascript -- I don't think you've raised against the right project...
