### ISSUE TITLE
Exception in StompReceiverThread - when receiving gzip file

### ISSUE THREAD

**Issue by davidnoguerol** [jasonrbriggs/stomp.py#147]
This is my first time raising an issue here, I appologise in advance if I haven't followed any rules or guidelines, feedback is always welcome.

I have used the code sample [dealing with disconnects](http://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects). It successfully connects. However, it encounters the following issue when receiving the data:

`Exception in thread StompReceiverThread-1:`
`Traceback (most recent call last):`
  `File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner self.run()`
  `File "C:\Python36\lib\threading.py", line 864, in run self._target(*self._args, **self._kwargs)`
  `File "C:\Python36\lib\site-packages\stomp.py-4.1.17-py3.6.egg\stomp\transport.py", line 334, in __receiver_loop`
    `f.body = decode(f.body)`
  `File "C:\Python36\lib\site-packages\stomp.py-4.1.17-py3.6.egg\stomp\backward3.py", line 29, in decode
    return byte_data.decode()`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte`

All messages in the stream are sent in XML with the message body compressed using gzip.

I believe that is an issue with the library not being able to handle the data in the stream, please tell me if I'm wrong.

Thanks in advance.

**Comment by jasonrbriggs** [comment]
Are you sure it's not an issue with the message broker?  There's a unit test which transmits an image file, and that seems to work fine (see test_image_send here: https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/test/p3_nonascii_test.py).  As a matter of interest I added a gzip test and it worked exactly the same.

**Comment by davidnoguerol** [comment]
I didn't see any explanation of some `stomp.Connection` parameters on the documentation but I guess they are self-explanatory. I added `auto_decode=False` and it worked perfectly fine.
Thanks Jason.

**Comment by jasonrbriggs** [comment]
Documented as a part of the Transport class: http://jasonrbriggs.github.io/stomp.py/stomp.html#module-stomp.transport. But it's probably not particularly obvious...
