### ISSUE TITLE
is it possible to create a queue using a stomp client

### ISSUE THREAD

**Issue by Dibyojyoti** [jasonrbriggs/stomp.py#148]
Hello,
Like in Java we create queues and topics and subscribe and send messages. in stomp I can see we are able to subscribe and send messages. But can we create a topic or queue from a python client?

**Comment by jasonrbriggs** [comment]
It's a naming convention.

/topic/topicname
/queue/queuename

Should be automatically created -- but it's dependent on the message broker, I guess.  Nothing to do with the client.
