### ISSUE TITLE
Stomp connection hangs forever

### ISSUE THREAD

**Issue by sugarfree1** [jasonrbriggs/stomp.py#150]
Hello, @jasonrbriggs 
I encountered a problem with ```StompConnection11``` protocol during connection establishment. Class ```Protocol11``` implements ```connect``` method with arbitrary parameter ```wait```.
If I create a connection with ```wait=True``` and try to connect to a server socket then the connection waits forever. I created server socket manually using python script:
```
import socket
serversocket = socket.socket(
    socket.AF_INET, socket.SOCK_STREAM)
serversocket.bind((socket.gethostname(), 61619))
serversocket.listen(1)
(sock, addr) = serversocket.accept()
```
It looks like it is stuck in that place in ```transport.py```:
```
            while not self.is_connected() and not self.connection_error:
                self.__connect_wait_condition.wait(wait_time)
```
because it is not connected yet and no connection error exists.
Is it an expected behaviour? If not, I can send you a pull request with fix.

**Comment by jasonrbriggs** [comment]
Sounds more like expected behaviour to me.  The connection is established, but there's been no valid response (in terms of a CONNECTED frame response from the server).  So it's not properly connected nor is there actually an error.  So it should wait under these circumstances, I think.

**Comment by sugarfree1** [comment]
Thanks for reply! I understand and respect your idea. But what if other server has network problems or something else (shutdown unexpectedly)? Client process would wait until socket is closed by OS (default timeout on Unix systems is 7200 seconds).

**Comment by elyssonmr** [comment]
I think I'm having this issue. 
When my rabbit server is down I have a really bad time to reconnect (the only solution so far is to restar my docker container)
Is this the same problem?

**Comment by jasonrbriggs** [comment]
I think PR https://github.com/jasonrbriggs/stomp.py/pull/156 fixes this. Or at least, without a specific test case which demonstrates the issue, I don't believe this will ever get addressed (at least by me).
