### ISSUE TITLE
security issue: do not log passcode header

### ISSUE THREAD

**Issue by coopstah13** [jasonrbriggs/stomp.py#152]
I'm using logging, and I saw this message in my log:

`Sending frame: 'STOMP', headers={'passcode': 'mypasscode', 'login': `myusername', 'accept-version': '1.1'}`

This is a security vulnerability as an attacker gaining access to the log could get credentials. Either do not log headers, or filter out sensitive headers before logging them.

**Comment by jasonrbriggs** [comment]
Fixed in .18 version (at least the most gregarious example)
