### ISSUE TITLE
Unrecoverable stomp connection hangs forever

### ISSUE THREAD

**Issue by Anthchirp** [jasonrbriggs/stomp.py#155]
This is related to, but not identical to #150.

If I connect to a "stomp server", that accepts connections, but never replies anything, ie.
```
$ nc -l 61613
```
stomp.py waits forever, as described in #150. 

If at this point I kill the server and close the connection stomp.py will notices the connection closing but will continue to wait. The situation is however unrecoverable, so stomp.py should no longer wait.

Log output:
```
Attempting connection to host localhost, port 61613
Established connection to host localhost, port 61613
Starting receiver loop
on_connecting localhost 61613
on_send STOMP {'passcode': 'password', 'login': 'admin', 'accept-version': '1.1'} 
Sending frame: ['STOMP', '\n', 'accept-version:1.1\n', 'login:admin\n', 'passcode:password\n', '\n', '\x00']

<< now Ctrl+C nc >>

on_disconnected
Receiver loop ended
```

Patch incoming.

**Comment by elyssonmr** [comment]
@Anthchirp do you think this issue could have a problem with reconnecting?
