### ISSUE TITLE
bad heartbeat timeout

### ISSUE THREAD

**Issue by yzfshuijing** [jasonrbriggs/stomp.py#159]
if set the stomp.Connection(self.address, heartbeats(3000,3000)),
everytime when recieved a msg from mq, then the heartbeats will be time out, the logs are below

Wed, 16 Aug 2017 16:52:00 transport.py[line:187] INFO Received frame: 'MESSAGE', headers={'expires': '0', 'timestamp': '1502873520099', 'destination': '/queue/WEBAPP_UPDATE_REQUEST_4KNOW', 'persistent': 'true', 'priority': '4', 'message-id': 'ID:ip-192-168-10-24-39856-1502873471740-3:1:1:1:1', 'subscription': '1'}, len(body)=1100
Wed, 16 Aug 2017 16:52:02 transport.py[line:267] INFO Sending frame: 'heartbeat', headers={}
Wed, 16 Aug 2017 16:52:04 listener.py[line:286] WARNING Heartbeat timeout: diff_receive=4.50221204758, time=1502873524.61, lastrec=1502873520.1

**Comment by yzfshuijing** [comment]
@jasonrbriggs

**Comment by yzfshuijing** [comment]
according to the test, i found that if send a heartbeat, and then recieved a msg, the mq would not send a response to answer the hearbeat we sended before, so the program thought the heartbeat timeout.

**Comment by jasonrbriggs** [comment]
Not sure I understand the problem you're hitting.  Heartbeats are definitely reset on message receipt.  That shouldn't result in a timeout.  I've tried a number of times to reproduce (with ActiveMQ for example) -- but it seems to work as expected.
