### ISSUE TITLE
stomp SSL

### ISSUE THREAD

**Issue by kshravank111** [jasonrbriggs/stomp.py#172]
I'm using stomp 3 due to some compatibility issues in environment, 
can anyone explain me how to add ssl to python stomp client i'm using. i added the stomp+ssl transport connector in activeMQ conf file

and my basic python stomp client is below:

    import time
    import sys
    import stomp
    class MyListener(stomp.ConnectionListener):
        def on_error(self, headers, message):
            print('received an error "%s"' % message)
        def on_message(self, headers, message):
            print('received a message "%s"' % message)
    conn = stomp.Connection()
    conn.set_listener('', MyListener())
    conn.start()
    conn.connect('admin', 'password', wait=True)
    conn.subscribe(destination='/queue/test', id=1, ack='auto')
    conn.send(body=' '.join(sys.argv[1:]), destination='/queue/test')
    time.sleep(2)
    conn.disconnect()

i created keystore and truststore given in http://activemq.apache.org/how-do-i-use-ssl.html docs and added them to SSL_OPTS environment variable in broker. But i'm unable to find how to initialize python stomp client with keystore and truststore given in docs. Should i use the SSL paraments given in stomp.Connection() method , if yes how to use??

Can anyone please explain if there is any other way to add ssl over stomp ?

**Comment by jasonrbriggs** [comment]
https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/test/ssl_test.py

**Comment by borislitvak** [comment]
The key point is understanding the key/cert files must be there - otherwise even stomp.py tests in their repository will not work. TLS will not work in stomp.py if the file names are not specified (correctly).

See the code & key generation instructions here: https://gist.github.com/borislitvak/6ccea503abf1b2f9c89e87309d6dab88
