### ISSUE TITLE
Thread control

### ISSUE THREAD

**Issue by miked63017** [jasonrbriggs/stomp.py#178]
Hi,

Thanks for the great module!

I am wondering if there is a way to control the number of threads that are spawned while listening, or for that matter disable threads all together?

Please ket me know.

Thanks!

**Comment by jasonrbriggs** [comment]
Well there's a single loop for receiving messages - after which there's no further thread creation unless the client does so.  You can control the mechanism by which threads are created by providing a thread creation function to the connection via `override_threading`.  So while there needs to be one thread for message receipt, you can control how that's created.
