### ISSUE TITLE
Additional grace for received heartbeat timeouts should be alterable

### ISSUE THREAD

**Issue by scottfweintraub** [jasonrbriggs/stomp.py#179]
Our current Artemis implementation appears to skip the occasional heartbeat.  If there were a way to alter the default "1.5" scale factor applied to the heartbeat receive timeout, this could prevent unnecessary disconnects for missed hearbeats.

**Comment by jasonrbriggs** [comment]
https://github.com/jasonrbriggs/stomp.py/pull/180
