### ISSUE TITLE
[stomp.py] Receiver loop ended (and gevent)

### ISSUE THREAD

**Issue by alvinyue** [jasonrbriggs/stomp.py#18]
On linux, not sure if there is a problem with stomp.py v4.0.12 and gevent 0.13.7. When the remote ActiveMQ server was down or restarted. Server logs recorded "Receiver loop ended". However, the listener registered with the connection doesn't get  on_disconnected() triggered. When stomp.py decided to disconnect, on_disconnected() will be called but doing

```
  for n in range(1,3):
        try:
            self.conn.set_listener()
            self.conn.set_listener("JMSListener", self)
            self.conn.stop()
            self.conn.start()
            self.conn.connect(wait=False)
            print "Connected?"
            break
        except Exception:
            print "Reconnect attempt failed:"
            time.sleep(1)
```

does not resume connection. The conn.send calls after that will get NotConnectedException

Currently, I work around the issue by try/except on conn.send() and do the connection code above inside except to restore connection but I probably lost 1 or more send before connection is restored.

So issue 1) Receiver loop ended does not trigger listener method. Issue 2) can't get reconnection code inside listener to really connect.

Finally, understand that app level reconnect had different approaches but can the stomp.py provide a default implementation or recipe to do it the basic/working way?

Thank you!

**Comment by jasonrbriggs** [comment]
Documentation for reconnecting has belatedly (belatedly! 2 years later!!) been added here: http://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects
