### ISSUE TITLE
Wiki Example doesn't run

### ISSUE THREAD

**Issue by omkarnathsingh** [jasonrbriggs/stomp.py#181]
Please check the check code in Wiki. The import stomp shows error.

**Comment by jasonrbriggs** [comment]
Not sure what you're doing but it seems fine to me with a clean env:

```
(python3.5test) jasonbriggs@beaglebone:~$ python
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stomp
>>>
```

**Comment by omkarnathsingh** [comment]
Fixed for me too. Actually I was doing pip install stomp, instead of pip install stomp.py. Thanks for the library.
