### ISSUE TITLE
doubt on executing 'nack' command in command-line client

### ISSUE THREAD

**Issue by cmsland** [jasonrbriggs/stomp.py#185]
https://github.com/jasonrbriggs/stomp.py/blob/779706ffb98866b4f7afb6f8960053e93f2e992a/stomp/__main__.py#L406

This would raise an exception because connection.nack() doesn't accept "headers" parameter. Is this intended?

**Comment by jasonrbriggs** [comment]
fixed here: https://github.com/jasonrbriggs/stomp.py/pull/189
