### ISSUE TITLE
`import stomp` takes long time when connected to ad-hoc network

### ISSUE THREAD

**Issue by Hunter522** [jasonrbriggs/stomp.py#186]
When I `import stomp` in a simple python program, it seems to take at least 10-15 seconds on my Windows 10 laptop to actually load the module. I noticed this only happens if I am connected directly to a ad-hoc WiFi network hosted by a Raspberry Pi 3. Doesn't happen if disconnect completely (turn off WiFi adapter). Strange...

I narrowed it down to this particular section of code in `stomp/utils.py:12`:

```
# List of all host names (unqualified, fully-qualified, and IP
# addresses) that refer to the local host (both loopback interface
# and external interfaces).  This is used for determining
# preferred targets.
LOCALHOST_NAMES = ["localhost", "127.0.0.1"]

try:
    LOCALHOST_NAMES.append(socket.gethostbyname(socket.gethostname()))
except:
    pass

try:
    LOCALHOST_NAMES.append(socket.gethostname())
except:
    pass

try:
    LOCALHOST_NAMES.append(socket.getfqdn(socket.gethostname()))
except:
    pass
```
It seems `LOCALHOST_NAMES.append(socket.getfqdn(socket.gethostname()))` is the culprit. I'm not entirely sure what this helps with, are there localhost names other than `localhost` and `127.0.0.1`? 

Workaround for me is to comment this section of code out (leaving the `LOCALHOST_NAMES = ["localhost", "127.0.0.1"]`).

OS: Windows 10 64-bit
Interpreter: Python 3.6.4 64-bit

**Comment by jasonrbriggs** [comment]
LOCALHOST_NAMES would also include your local network IP address, plus local domain name.

Everything I've read about slow `getfqdn` suggests this is an issue with your DNS.  So not convinced there's a fix required to stomp.py for this.

**Comment by Hunter522** [comment]
Gotcha, thanks for the information @jasonrbriggs
