### ISSUE TITLE
receiver_loop_completed

### ISSUE THREAD

**Issue by clusby** [jasonrbriggs/stomp.py#187]
From this commit:
https://github.com/jasonrbriggs/stomp.py/commit/9247916e58335a69f763a959e173bab0d5585e9c

I think ```on_receiver_loop_completed()``` needs to be added to the ```ConnectionListener``` class?

On disconnect, I am seeing warnings logged like:
```DEBUG: listener <stomp.connect.StompConnection11 object at 0x0399A650> has no method on_receiver_loop_completed```

**Comment by jasonrbriggs** [comment]
Thx for the report.
