### ISSUE TITLE
race condition during shutdown

### ISSUE THREAD

**Issue by marojor** [jasonrbriggs/stomp.py#19]
While executing the example provided in the front page (https://github.com/kwoli/stomp.py/wiki/Simple-Example), sometimes the process ends-up throwing following exception:

Exception in thread Thread-1 (most likely raised during interpreter shutdown)

Looking at the code, it seems like a race condition during shutdown. The last thing the main thread does is stop the transport, that is, wait for the receiver thread to exit:

264     def stop(self):
265         """
266         Stop the connection. Performs a clean shutdown by waiting for the
267         receiver thread to exit.
268         """
269         self.__receiver_thread_exit_condition.acquire()
270         while not self.__receiver_thread_exited:
271             self.__receiver_thread_exit_condition.wait()
272         self.__receiver_thread_exit_condition.release()

Problem is the receiver thread after setting the exit condition, still tries to log some info:

509         finally:
510             self.__receiver_thread_exit_condition.acquire()
511             self.__receiver_thread_exited = True
512             self.__receiver_thread_exit_condition.notifyAll()
513             self.__receiver_thread_exit_condition.release()
514             log.info("Receiver loop ended")

Thus, if the main thread is fast enough, it finish before the receiver thread (which is set as daemon thread), and the intepreter raise an exception during shutdown.

**Comment by jasonrbriggs** [comment]
I'm moving the log message up to before the notify... which might help, but not sure as I've never been able to reproduce this error.
