### ISSUE TITLE
'NoneType' object has no attribute 'sendall'

### ISSUE THREAD

**Issue by miguelgr** [jasonrbriggs/stomp.py#191]
Shouldn't it be check also inside the semaphore context manager?

![image](https://user-images.githubusercontent.com/1484589/37608741-9f109938-2b9b-11e8-8045-64dd84a1c539.png)

**Comment by jasonrbriggs** [comment]
Why?  The semaphore is only used to ensure there's only one send at a time, not the ensure the socket is still accessible.  Even if the check is added inside the semaphore context, you could still see the issue if the cleanup happens between semaphore context and call to `sendall`.  I guess a check to self.running might work -- but need a bit more info as to the scenario where you see this error...?
