### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by m3nthal** [jasonrbriggs/stomp.py#195]
```Python
def decode(byte_data):
    """
    Decode the byte data to a string if not None.

    :param bytes byte_data: the data to decode

    :rtype: str
    """
    if byte_data is None:
        return None
    return byte_data.decode()
```

when receives `byte_data = b'\xf0\x01ActiveMQ'` raises:

> stomp/backward3.py", line 29, in decode
>     return byte_data.decode()
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

https://docs.python.org/3/library/stdtypes.html#bytes.decode
This could be fixed to by changing errors parameter from default `errors="strict"`:
```
>>> b'\xf0\x01ActiveMQ'.decode(errors="ignore")
'\x01ActiveMQ'
>>> b'\xf0\x01ActiveMQ'.decode(errors="replace")
'�\x01ActiveMQ'
>>> b'\xf0\x01ActiveMQ'.decode(errors="strict")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte
```

**Comment by jasonrbriggs** [comment]
I think I've fixed the issue here: https://github.com/jasonrbriggs/stomp.py/pull/200

**Comment by sanghaimuskan** [comment]
utf-8' codec can't decode byte 0xf0 in position 1718: invalid continuation byte

I am fetching this error:
code:

clip = mp.VideoFileClip(r"no.mp4") 
 
clip.audio.write_audiofile(r"no.wav")
and the video file is fine.

**Comment by jasonrbriggs** [comment]
Failing to see what your code excerpt has to do with stomp.py
