### ISSUE TITLE
half a deadlock in transport.py

### ISSUE THREAD

**Issue by Anthchirp** [jasonrbriggs/stomp.py#197]
I am using stomp.py in a context where I am using a reentrant lock (threading.RLock()) to ensure thread-safe access to the stomp Connection object, so all calls follow the pattern
```python
with lock:
  conn.(...)
```

After the update to 4.1.20 I noticed that sometimes my application would simply stop, and after much trial-and-error I identified https://github.com/jasonrbriggs/stomp.py/commit/f291bfa98d73cbbc7441ce3e5107928f389b67c4 / https://github.com/jasonrbriggs/stomp.py/pull/174 to be the cause. What happens is that the main thread tries to send a message, while the receiver thread processes an incoming message at the same time.

The main thread acquires my lock, and the ```.send()``` call ends up in https://github.com/jasonrbriggs/stomp.py/blob/f986bd500e1cd286683555464668141e738066ef/stomp/transport.py#L250-L256 and waits for the ```__listeners_change_condition``` lock.
Meanwhile the ```StompReceiverThread``` receives the message, goes into ```notify()```, and acquires the ```__listeners_change_condition``` lock, https://github.com/jasonrbriggs/stomp.py/blob/f986bd500e1cd286683555464668141e738066ef/stomp/transport.py#L224 which calls my ```.on_message``` handler. I try to access the stomp connection object at this point and both threads end up in a permanent deadlock.

While it would be sufficient to just change my code to avoid the deadlock, I would also like to break the deadlock on the stomp.py side. Here the pattern is generally
```python
with self.__listeners_change_condition:
   for listener in self.listeners.values():
```
Unfortunately it is not quite clear what the intention of the lock is? Is it to simply deny changing the dictionary while it is being evaluated, or is it to hold any thread trying to change the dictionary until the evaluation is complete? If it is the former then it may be reasonable to give up the lock early:
```python
with self.__listeners_change_condition:
   listeners = self.listeners.values()
for listener in listeners:
```
or alternatively avoiding dictionary views on python 3 and using a static list at the time of the lock:
```python
with self.__listeners_change_condition:
   listeners = list(self.listeners.values())
for listener in listeners:
```

**Comment by jasonrbriggs** [comment]
The original intention was to stop modifications to the listeners while they were being evaluated, so I think your idea of a static list is the best one.  Have updated here: https://github.com/jasonrbriggs/stomp.py/pull/198
