### ISSUE TITLE
timeout is breaking the existing connection.

### ISSUE THREAD

**Issue by unnobtainium** [jasonrbriggs/stomp.py#201]
Hello,

I am creating a stomp connection using timeout=2 seconds with some retry logic(if connection is absent). The connection is created successfully but this is also causing the on_disconnect call every 2 seconds.

I thought timeout was there to wait until connection is made.
I am using stomp.py v4.1.20

**Comment by jasonrbriggs** [comment]
That's a socket timeout, not the connection wait timeout.

**Comment by unnobtainium** [comment]
How to I apply connection wait timeout? Thanks.

**Comment by jasonrbriggs** [comment]
The functionality is not currently available.
