### ISSUE TITLE
Dealing with disconnects example is broken

### ISSUE THREAD

**Issue by leonidumanskiy** [jasonrbriggs/stomp.py#202]
["Dealing with disconnects" example](http://jasonrbriggs.github.io/stomp.py/api.html#dealing-with-disconnects) provided in the documentation seems to be broken.

After trying to run this example, provided code goes into infinite loop trying to connect and reconnect, looping between `stomp.exception.NotConnectedException` and `stomp.exception.ConnectionClosedException`.

After quick investigation it seems like there is a logic mistake in the transport class:
```
except exception.ConnectionClosedException:
    if self.running:
        #
        # Clear out any half-received messages after losing connection
        #
        self.__recvbuf = b''
        self.running = False
        self.notify('disconnected')
    break
finally:
    self.cleanup()
```
cleanup() function is called after it notifies the listener and calls disconnect(), therefore it sets self.socket = None after the reconnect code was invoked.

The following change seems to fix the problem:

```
    if self.running:
        #
        # Clear out any half-received messages after losing connection
        #
        self.__recvbuf = b''
        self.running = False
        self.cleanup()
        self.notify('disconnected')
    break    
```

**Comment by jasonrbriggs** [comment]
This change looks to fix the problem: https://github.com/jasonrbriggs/stomp.py/pull/207
