### ISSUE TITLE
Make heartbeat grace period configurable

### ISSUE THREAD

**Issue by elliotbc** [jasonrbriggs/stomp.py#203]
Making the heartbeat grace period configurable would allow the user to be more or less strict on the heartbeat timing, and it would allow them to use heartbeats with broken ActiveMQ.

Here's the details of the ActiveMQ's issue. In short, heartbeats may be up to 2x the heartbeat interval apart, which doesn't work with the hardcoded 1.5x allowed in stomp.py:
https://issues.apache.org/jira/browse/AMQ-4710

**Comment by jasonrbriggs** [comment]
`heart_beat_receive_scale` is already available on the connection. Seems to me this is already configurable...?
