### ISSUE TITLE
we lose messages when sending to rabbitmq

### ISSUE THREAD

**Issue by agalera** [jasonrbriggs/stomp.py#210]
We have been observing a rather strange case for a while.

We have a log that indicates when we have sent a message, with an ID, but sometimes, that message that has been sent in theory, is never consumed, nor is it in the queue.

The theory that I have (I've been looking at the lib code a bit) is that we send the frame, but we do not check what the server responds to.

My question is, does the send function secure its delivery? or something else to do.

Thanks

**Comment by jasonrbriggs** [comment]
Belatedly, you can use receipts: https://stomp.github.io/stomp-specification-1.1.html#RECEIPT

But can't think of a reason for a message not to be consumed even if you don't use receipts.  Not convinced it's a stomppy issue though on the face of it...
