### ISSUE TITLE
stomp.py posts not readable by Apache.NMS

### ISSUE THREAD

**Issue by RickdeGier** [jasonrbriggs/stomp.py#211]
I have the ActiveMQ broker running on a Linux server, and I can produce and consume wit stomp.py as well as with Apache.NMS. If I produce a message at Apache.NMS and consume at stomp.py it just works. The problem is when I produce with stomp.py the message is ignored in Apache.NMS or the text is empty. It ignores when leaving out the .join(sys.argv[1:]) and it has an empty text when it is present.
I think my problem has something to do with flags or setting on the stomp.py side or at the Apache.NMS side.

I am using the example from [Apache.NMS: http://activemq.apache.org/nms/examples.html](url)

conn = Connection(host_port)
conn.set_listener('listener', MyListener())
conn.start()
conn.connect('admin', 'admin')
conn.subscribe(destination='/queue/CSharp', id=0)
conn.send(destination='/queue/Python', body='Python-0', persistent=True)

**Comment by jasonrbriggs** [comment]
Do you have the same issue with the ActiveMQ broker on Linux? Or only on NMS?

**Comment by RickdeGier** [comment]
I found the error the ActiveMQ.NMS software expected '\r\n' on the end of an message while python does not.
