### ISSUE TITLE
BaseTransport.__disconnect_receipt is set only in __init__

### ISSUE THREAD

**Issue by kokorin** [jasonrbriggs/stomp.py#212]
Hi, great library, I was even able to combine stomp.py and websocket-client to implement stomp.js client.

Today I faced an issue with DISCONNECT frame, I see disconnect RECIEPT received, but the following condition is always false: 

```
# BaseTransport.notify()
# received a stomp 1.1+ disconnect receipt
if receipt == self.__disconnect_receipt:
    self.disconnect_socket()
```

**Comment by jasonrbriggs** [comment]
To be resolved in the next version (see PR: https://github.com/jasonrbriggs/stomp.py/pull/230)
