### ISSUE TITLE
Can stomp.py support stomp-over-websockt

### ISSUE THREAD

**Issue by casper1314** [jasonrbriggs/stomp.py#214]
Dear experts:

I have a requirement to connect to websocket using python. When I use this python library to connect, connection failed all the time. Not like the javascript lib stomp.js, the stomp.py can not specify websocket protocol in url, the activemq service reports that a http channel over http was connected.

Do you have any idea about that? Thanks.

**Comment by jasonrbriggs** [comment]
websocket has an http handshake before switching to a binary protocol -- there's nothing in stomppy designed to communicate over this.
