### ISSUE TITLE
stomp.Connection should support with-statement context interface

### ISSUE THREAD

**Issue by aparamon** [jasonrbriggs/stomp.py#215]
Currently, the following statement fails:
````python
with stomp.Connection() as stomp:
    ...
````
````pytb
AttributeError: __enter__
````
It is proposed that `stomp.Connection` implements `__enter__`/`__leave__`, with the latter `disconnect()`ing the connection.

**Comment by jasonrbriggs** [comment]
Resolved in the next release.
