### ISSUE TITLE
Do not set content-length for text messages

### ISSUE THREAD

**Issue by aparamon** [jasonrbriggs/stomp.py#216]
As per http://activemq.apache.org/stomp.html
> **Working with JMS Text/Bytes Messages and Stomp**
>
> Stomp is a very simple protocol - that's part of the beauty of it! As such, it does not have knowledge of JMS messages such as TextMessage's or BytesMessage's. The protocol does however support a content-length header. To provide more robust interaction between STOMP and JMS clients, ActiveMQ keys off of the inclusion of this header to determine what message type to create when sending from Stomp to JMS. The logic is simple:
>
> Inclusion of content-length header | Resulting Message
> -- | --
> yes | BytesMessage
> no | TextMessage

By default however, `stomp.Connection.send()` always specifies content-length header. The workaround is `stomp.Connection(auto_content_length=False)`, but this instructs the connection to *never* specify content-length which is also sub-optimal.

It is proposed that `stomp.Connection(auto_content_length=True)` (the default) specifies the content-length header only for `bytes` messages and not for `str` messages.

**Comment by jasonrbriggs** [comment]
This is activemq (and as a consequence java/jms) specific, so not something I think needs to be added to stomp.py.  My suggestion would be set auto_content_length to False, and then provide the content-length yourself as a header depending on what type of message you're sending.
