### ISSUE TITLE
Support waiting for receipt after sending a message

### ISSUE THREAD

**Issue by mprahl** [jasonrbriggs/stomp.py#224]
I'm in the process of migrating an app from stomp.py v3 to v4. One thing I noticed is that `wait_on_receipt` is deprecated and is now a "no-op". Could you please make stomp.py block until the server acknowledges the processing of the message after a message is sent like it did in v3?

Here is the old `send` method that had this implemented:
```python
def send(self, message='', headers={}, **keyword_headers):
    """
    Send a message (SEND) frame
    """
    merged_headers = utils.merge_headers([headers, keyword_headers])
    wait_on_receipt = self.__wait_on_receipt and 'receipt' in merged_headers.keys()
    if wait_on_receipt:
        self.__send_wait_condition.acquire()
    try: 
        self.__send_frame_helper('SEND', message, merged_headers, [ 'destination' ])
        self.__notify('send', headers, message)

        # if we need to wait-on-receipt, then block until the receipt frame arrives 
        if wait_on_receipt:
            receipt = merged_headers['receipt']
            while receipt not in self.__receipts:
                self.__send_wait_condition.wait()
            del self.__receipts[receipt]
    finally:
        if wait_on_receipt:
            self.__send_wait_condition.release()
```

Thank you for your help.

**Comment by mprahl** [comment]
Alternatively, is there a way to respond to an error frame being returned by the server?

**Comment by jasonrbriggs** [comment]
@mprahl There's no changes required to stomp, you can just use stomp.listener.WaitingListener and wait on the receipt. You can see an example of this here: https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/test/apollo_test.py

That's using a TestListener but the basic principle is the same.
