### ISSUE TITLE
Change a few transport log records from INFO to DEBUG level

### ISSUE THREAD

**Issue by amaltaro** [jasonrbriggs/stomp.py#226]
Hello, once I started using this library version 4.1.15, I noticed it's quite verbose and the `transport` module prints quite some data at INFO level, one of them being actually very undesirable, since it can actually throw your AMQ credentials into the logs, e.g.:
https://github.com/jasonrbriggs/stomp.py/blob/v4.1.15/stomp/transport.py#L256

I found a way to overwrite the `stomp.py` log level, but I believe it would be better to get this eventually fixed upstream. Thanks

**Comment by jasonrbriggs** [comment]
Will be updated in the next version - see here for an example: 

https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/transport.py#L274
