### ISSUE TITLE
how to set message‘s header to persistent messages when send message to activemq

### ISSUE THREAD

**Issue by LegolasShaw** [jasonrbriggs/stomp.py#227]
hello, i want to set my message persistent when i send message to activemq, but i do not how to set headers in function send. i find document  in activemq official website  it says 

“Persistent Messaging in STOMP
STOMP messages are non-persistent by default. To use persistent messaging add the following STOMP header to all SEND requests: persistent:true. This default is the opposite of that for JMS messages.” and then i set headers = {"persistent": true}, but it do not work 。 and i find the key word in code , i can not find key word "persistent", please help me.

**Comment by jasonrbriggs** [comment]
The persistent header is nothing to do with STOMP itself -- it's an activemq thing -- so you won't find it in the stomp.py code.

Either of these methods work fine for me:

1.
```
conn.send(body='this is a test', destination='/queue/test', receipt='123', headers = {"persistent":"true"})

MESSAGE
content-length: 14
expires: 0
destination: /queue/test
subscription: 1
priority: 4
message-id: ID:1b923c444d0e-33115-1545502976158-3:10:-1:1:1
anotherheader: blah
persistent: true
timestamp: 1545508745228
this is a test
```

2.
```
conn.send(body='this is a test', destination='/queue/test', receipt='123', persistent="true")

MESSAGE
content-length: 14
expires: 0
destination: /queue/test
subscription: 1
priority: 4
message-id: ID:1b923c444d0e-33115-1545502976158-3:11:-1:1:1
persistent: true
timestamp: 1545508847331
this is a test
```

**Comment by LegolasShaw** [comment]
it works! thx
