### ISSUE TITLE
STOMP Connection using URL, instead of IP and Port?

### ISSUE THREAD

**Issue by ccs1910** [jasonrbriggs/stomp.py#229]

**Comment by ccs1910** [comment]
hello, i am creating a chat-application using Stomp Over WebSocket. but i have a problem on using the STOMP.py that i can't establish connection to the WebSocket Endpoint. My websocket end-point is "https://chat-api.com/chat-api/websocket" and this is my code :  
import time
import sys

import stomp

from basicauth import encode

username = 'pmi-test'
password = 'qxsaddaqwqewqdq'
URL_wss = 'wss://chat-euapi.com/chat-api/websocket'
URL = "https://chat-euapi.com/chat-api/websocket"
encoded_str = encode(username, password)

# test connection


class MyListener(stomp.ConnectionListener):
    def on_error(self, headers, message):
        print('received an error %s' % message)
    def on_message(self, headers, message):
        for k,v in headers.iteritems():
            print('header: key %s , value %s' %(k,v))
        print('received message\n %s'% message)

conn = stomp.Connection([('wss://chat-euapi.com/chat-api', 433)])
print('set up Connection')
conn.set_listener('somename',MyListener())
print('Set up listener')

conn.start()
print('started connection')

receivedest = 'user/chat-receive'
conn.connect(wait=True, headers={'Authorization': encoded_str})
print('connected')
conn.subscribe(destination=receivedest, ack='auto')
print('subscribed')

message_body = {
                    "type" : "CONNECT",
                    "from" : "CustomerFrancis",
                    "serviceUuid": "6b6e5fda-ed70-44df-baf3-109d3892c20f",
                    "commandId": 1,
                    "customData": {
                                "userDefined12": "companyCode",
                                "userDefined13": "email@example.com",
                                "userDefined15": "ticketReference"
                        
                    }
                }
conn.send(body=message_body, destination='/chat/chat-send', headers={'Authorization': encoded_str})

time.sleep(2)
conn.disconnect()

class MyListener(stomp.ConnectionListener):
    def on_error(self, headers, message):
        print('received an error "%s"' % message)
    def on_message(self, headers, message):
        print('received a message "%s"' % message)

conn = stomp.Connection()
conn.set_listener('', MyListener())
conn.start()
conn.connect('admin', 'password', wait=True)

conn.subscribe(destination='/queue/test', id=1, ack='auto')

conn.send(body=' '.join(sys.argv[1:]), destination='/queue/test')

time.sleep(2)
conn.disconnect()

how basically to do STOMP.Connection using URL instead of IP and POrt?

**Comment by jasonrbriggs** [comment]
Stomp.py is not designed to work with websockets.
