### ISSUE TITLE
4.1.22 not quite backward compatible

### ISSUE THREAD

**Issue by singlaive** [jasonrbriggs/stomp.py#238]
After a weekend sadly found my service was broken, since it relies on the latest stomp.py and 4.1.22 drops the wait_on_receipt argument for Connection classes. 

Could please kindly clarify what is the alternative method for the previous wait_on_receipt flag? It would be even better to throw a deprecated warning when people attempt to pass this unused argument in, rather than simply dropping it.

**Comment by jasonrbriggs** [comment]
It wasn't "simply dropped".  `wait_on_receipt` has been marked as deprecated since Oct 2016.  In fact setting the parameter has had no effect since then.  The alternative is a waiting listener of some kind (some info here: https://github.com/jasonrbriggs/stomp.py/issues/224)

**Comment by singlaive** [comment]
Thank you!
