### ISSUE TITLE
I want to get a long connection.

### ISSUE THREAD

**Issue by xinghailong** [jasonrbriggs/stomp.py#24]
I want to get a long connection.
How?
like Stomp.connect(username=None, password=None, clientid=None)

**Comment by xinghailong** [comment]
Hi, stompy can use "clientid" to connect old connection, but I can not find the relevant parameter of stom.py. So I want to know how can I find that ?

**Comment by xinghailong** [comment]
I want  to use the persistent connection to send message, I do not want the "start" "connect" "disconnect" appear frequently.

**Comment by jasonrbriggs** [comment]
I believe clientid is something activemq specific.  It's not a stomp header. So there is no relevant parameter.  I you check the API documentation (http://jasonrbriggs.github.io/stomp.py/classstomp_1_1protocol_1_1_protocol12.html) you'll see that you can send arbitrary headers using the headers parameter.

As for persistent connections, the connection will stay open as long as the server allows.

**Comment by xinghailong** [comment]
class MyListener(object):
        def __init__(self,conn):
            self.conn = conn

        def on_message(self, headers, message):
            # some data processing for message
            send_msg = json.dumps(send_msg)

            # send to next queue
            dest = '/queue/smtp'
            ef.sendMessage(send_msg,dest,self.conn)


    def branch(i,stomp_host):
        if stomp_host != None:
            #get message from JMS
            conn = stomp.Connection([(stomp_host[0],stomp_host[1])],user=stomp_host[2],passcode=stomp_host[3])
            conn.set_listener('', MyListener(conn))
            conn.start()
            conn.connect(wait=True)
            conn.subscribe(headers={'destination':'/queue/edm','activemq.prefetchSize':1, 'ack':'auto'})
            time.sleep(1)
            #conn.disconnect()
            while True:
                try:  
                    time.sleep(1)  
                except:  
                    break
        else:
            ef.edmLogs('stomp_host error branch','sysLog.log')

Use “conn”  to send message，but sometimes it do not work. Can you give me some suggestions?

测试环境没问题，正式环境不行，还真是头疼！
