### ISSUE TITLE
`subscription` argument of the `ack` method only present for Stomp 1.1

### ISSUE THREAD

**Issue by kkom** [jasonrbriggs/stomp.py#240]
Hi @jasonrbriggs ! Thanks for creating this awesome framework!

I realised that the `ack` method has the `subscription` parameter only for Stomp 1.1. For reference, here are the respective function interfaces:

Stomp 1.0:

https://github.com/jasonrbriggs/stomp.py/blob/643843c5fbf25fd24339dd0e69a9411c3d8b94c7/stomp/protocol.py#L53

Stomp 1.1:

https://github.com/jasonrbriggs/stomp.py/blob/643843c5fbf25fd24339dd0e69a9411c3d8b94c7/stomp/protocol.py#L263

Stomp 1.2:

https://github.com/jasonrbriggs/stomp.py/blob/643843c5fbf25fd24339dd0e69a9411c3d8b94c7/stomp/protocol.py#L456

I have two questions/remarks about it:

1. The online documentation/API reference seem to assume that we are using Stomp 1.1. This actually got me into trouble -- I was working with Stomp 1.2, and I kept setting the transaction ID instead of the subscription ID! I think it would be a good idea to clarify this a bit in the docs.
2. Is it the really the case that only Stomp 1.1 supports setting subscription ID in the ACK message? The server I'm connecting to seems to only accept ACK messages with a subscription ID. But I would like to use Stomp 1.2 -- I like to be on the newest version, if possible.

Best wishes,
Konrad

**Comment by jasonrbriggs** [comment]
1. Added a note to the documentation: http://jasonrbriggs.github.io/stomp.py/
2. Yes.  Compare the protocol documentation for [1.0](http://stomp.github.io/stomp-specification-1.0.html#frame-ACK), [1.1](http://stomp.github.io/stomp-specification-1.1.html#ACK) and [1.2](http://stomp.github.io/stomp-specification-1.2.html#ACK)
