### ISSUE TITLE
Publisher publishes 'byte' type data but consumer gets back unicode string

### ISSUE THREAD

**Issue by nikhil578** [jasonrbriggs/stomp.py#241]
Similar to https://github.com/jasonrbriggs/stomp.py/issues/107 

The problem happens with Python 3 where native string is unicode. If the publisher sends out a pickled object, the consumer is expected to get a byte-like object to unpickle.

Publisher
---------------
`conn.send('/queue/test', pickle.dumps(<some_obj>))`

Consumer
-------------
```
class ProcessListener(stomp.ConnectionListener):
    def on_message(self,headers,message):
        # I need to do pickle.loads(message) here

c.set_listener('',ProcessListener())
c.subscribe('/queue/test',id=1,headers=Headers)
```

Setting up `content-length` or `content_type` to `application/octet-stream` in the header doesn't work.

**Comment by jasonrbriggs** [comment]
Dupe issue to https://github.com/jasonrbriggs/stomp.py/issues/242. See that thread for more information.
