### ISSUE TITLE
stomp.py is converting bytes data to str data in python 3 on receiver side

### ISSUE THREAD

**Issue by choudhary001** [jasonrbriggs/stomp.py#242]
I am trying to send and receive bytes data in Python 3 using stomp.py. I am sending bytes data but on receiver side, I get str data.

From my investigation, the encode() function simply returns the data as it is if it is bytes data, however the decode() function in backward3.py is doing this conversion of bytes data to str data on receiver which is not desired if I want to receive bytes data.

Is there a way I can send and receive bytes data in Python 3 via stomp.py?

**Comment by choudhary001** [comment]
I found that I can disable the auto decoding using auto_decode=False while creating the Stomp Connection object. It works fine for me.

Is there a way, I can choose this behavior on a topic/queue subscription basis? For example, I subscribing to 2 topics and one of them sends bytes and one of them sends strings. If I set this on the Connection object, I suppose, I will always get a byte string.

**Comment by jasonrbriggs** [comment]
Why not just turn auto_decode off by default and then just handle in the listener with the content_type header? Or the destination header for that matter?

**Comment by choudhary001** [comment]
Thanks Jason! Will this work between JMS -> STOMP communication? I am using ActiveMQ and their documentation doesn't mention anything about content-type header. It does use content-length header to distinguish between bytes and text messages. Using destination header could be an option here.
