### ISSUE TITLE
Getting 2 disconnections instead of one in this simple example

### ISSUE THREAD

**Issue by jumbee126** [jasonrbriggs/stomp.py#245]
Hi,

I ran this simple example with Python 3.7.4 and stomp 4.1.22. I would expect only one disconnection as stats are displayed twice. Cannot you please explain this behaviour ? 
Is it something expected or/and can we avoid this ?
Thanks.

# Python 3.7.4
# stomp.py v4.1.22 (https://pypi.python.org/pypi/stomp.py)

import time
import stomp

class MyListener(stomp.ConnectionListener):
    def on_message(self, headers, message):
        print('MyListener:\nreceived a message "{}"\n'.format(message))
        global read_messages
        read_messages.append({'id': headers['message-id'], 'subscription':headers['subscription']})

class MyStatsListener(stomp.StatsListener):
    def on_disconnected(self):
        super(MyStatsListener, self).on_disconnected()
        #if self.disconnects == 1:
        print('MyStatsListener:\n{}\n'.format(self))

read_messages = []
hosts = [('localhost', 61614)]

conn = stomp.Connection(hosts)
conn.set_ssl(for_hosts=hosts)

conn.set_listener('my_listener', MyListener())
conn.set_listener('stats_listener', MyStatsListener())
conn.start()

user = 'user1'
pwd = 'pass1'

conn.connect(user, pwd, wait=True)
# wait=True means that it waits until it's established a connection with the server before returning.

# id should uniquely identify the subscription
# ack = auto, client, or client-individual
# See https://stomp.github.io/stomp-specification-1.1.html#SUBSCRIBE_ack_Header
conn.subscribe(destination='/queue/rdsqueue', id=1, ack='client-individual')
conn.send(body="A Test message", destination='/queue/rdsqueue')
time.sleep(3)
for message in read_messages:
    conn.ack(message['id'], message['subscription'])
conn.disconnect()

# Script output ...
#
# MyListener:
# received a message "A Test message"
#
# MyStatsListener:
# Connections: 1
# Messages sent: 5
# Messages received: 1
# Errors: 0

My output: 

MyListener:
received a message "A Test message"

MyStatsListener:
Connections: 1
Disconnects: 1
Messages sent: 5
Messages received: 1
Heartbeats received: 0
Errors: 0

MyStatsListener:
Connections: 1
Disconnects: 2
Messages sent: 5
Messages received: 1
Heartbeats received: 0
Errors: 0

Process finished with exit code 0

**Comment by jasonrbriggs** [comment]
Resolved with version 4.2.0
