### ISSUE TITLE
STOMP integrated with Django

### ISSUE THREAD

**Issue by willianantunes** [jasonrbriggs/stomp.py#249]
Hi, we made a public library using `stomp.py` integrated with Django to help the community with more samples about how to work with it thinking in production systems.

https://github.com/juntossomosmais/django-stomp

The project has [integration tests](https://github.com/juntossomosmais/django-stomp/tree/master/tests/integration) and use cases for [transactions](https://github.com/juntossomosmais/django-stomp/blob/ec55a0ef860f2ebef771a733209208267cfd5df9/django_stomp/services/producer.py#L119-L135) and [auto open/close logic](https://github.com/juntossomosmais/django-stomp/blob/ec55a0ef860f2ebef771a733209208267cfd5df9/django_stomp/services/producer.py#L109-L116) using context managers.

Also we created some abstractions classes ([Publisher](https://github.com/juntossomosmais/django-stomp/blob/ec55a0ef860f2ebef771a733209208267cfd5df9/django_stomp/services/producer.py#L21) and [Listener](https://github.com/juntossomosmais/django-stomp/blob/ec55a0ef860f2ebef771a733209208267cfd5df9/django_stomp/services/consumer.py#L36)) to handle `stomp.py` internals and a [Payload](https://github.com/juntossomosmais/django-stomp/blob/ec55a0ef860f2ebef771a733209208267cfd5df9/django_stomp/services/consumer.py#L28-L33), where it's used to deliver to the callback function.

This issue is just a news. Thank you very much for this fantastic lib!

**Comment by jasonrbriggs** [comment]
@willianantunes Thanks for the info. Added to the documentation here: http://jasonrbriggs.github.io/stomp.py/otherprojects.html
