### ISSUE TITLE
Possible race conditions in listener.py

### ISSUE THREAD

**Issue by ftesser** [jasonrbriggs/stomp.py#251]
I use [TestListener](https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/listener.py#L508) class to automatize some tests similarly to [activemq_test.py](https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/test/activemq_test.py).

Sometimes I run into some deadlocks, and after checking my code I started looking at stomp.py too.

I think there are some possible race conditions in [listener.py](https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/listener.py).

Pull requests will follow.

**Comment by ftesser** [comment]
As described in https://docs.python.org/3.7/library/threading.html#condition-objects 

> A condition variable obeys the context management protocol: using the with statement acquires the associated lock for the duration of the enclosed block. The acquire() and release() methods also call the corresponding methods of the associated lock.

In [listener.py](https://github.com/jasonrbriggs/stomp.py/blob/master/stomp/listener.py) some times the `with` block does not take into account the update of the locked variable.

**Comment by jasonrbriggs** [comment]
To be released in version 4.2.0 (in the new year)
