### ISSUE TITLE
How to integrate stomp listener with Flask app

### ISSUE THREAD

**Issue by guptakvgaurav** [jasonrbriggs/stomp.py#253]
I have flask app and stomp listener ready as 2 separate pieces, and I would like `my flask server to have a listener in it`.

Can you guide/present example on `how can one integrate stomp with Flask server`

Flask app
```

class EventManager(stomp.ConnectionListener):

    def on_message(self, headers, body):
        print('On message received')


def make_connection(app_event):
        event_name = app_event.get('name', None)
        queue_name = app_event.get('queue_name', None)

        connection = stomp.Connection()
        connection.set_listener(name=event_name, lstnr=EventManager())
        connection.connect('admin',  'admin', wait=True)
        connection.subscribe(destination=queue_name, id=event_name, ack='auto')
     return 

def create_app():
    app = Flask(__name__)
    # TODO: HOW CAN WE MAKE connection keep listening to the incoming messages.
    app_event = {
        'name': 'on_boarding_images',
        'queue_name': '/queue/ml_notification'
    }
    make_connection(app_event)
    if __name__ == '__main__':
        flask_app.run()
    return flask_app
```

Question: How can we make stomp connection keep listening to the incoming events. Their needs to be some way of integrating this.

Note: I have tried to demonstrate only relevant piece of information here as code snippet, it may not work as it is, but idea is to showcase what I would like to achieve.

**Comment by madkote** [comment]
>  Question: How can we make stomp connection keep listening to the incoming events. Their needs to be some way of integrating this.

please read docs.

> Flask

you would need a separate thread to receive messages. I would go for an extension.

**Comment by jasonrbriggs** [comment]
Closing as this isn't an issue with stomp.py
