### ISSUE TITLE
How does timeout option work in Connection

### ISSUE THREAD

**Issue by yiyang59** [jasonrbriggs/stomp.py#254]
I was trying to keep my connection live using this code:

conn = stomp.Connection([(srv, port)], timeout = 18000000, keepalive=True)

but it still gets disconnected after ~ 30min of inactivity. Am I doing something wrong? 

Thanks.

**Comment by jasonrbriggs** [comment]
I don't think setting a timeout guarantees the socket will be kept open.  That's what heartbeating was designed to do... http://stomp.github.io/stomp-specification-1.2.html#Heart-beating

**Comment by yuyiguo** [comment]
Then what is the timeout in the connection for?
