### ISSUE TITLE
Failover for brokers behind Load Balancers doesn't work

### ISSUE THREAD

**Issue by MauriceBrg** [jasonrbriggs/stomp.py#255]
Hey!

I'm not entirely sure if this is really an issue with the library or with my setup.

**Background**

I run a **Active/Standby** Amazon MQ (managed ActiveMQ) Broker behind a Network Load Balancer in AWS in an Architecture that is described in [this](https://aws.amazon.com/blogs/compute/creating-static-custom-domain-endpoints-with-amazon-mq/) AWS Blog.

I set up three DNS-Endpoints:

- broker.mydomain.com --> Points to the Loadbalancer
- broker1.mydomain.com --> Points to the LB-Endpoint that sits in front of Broker Node A
- broker2.mydomain.com --> Points to the LB-Endpoint that sits in front of Broker Node B

**Code**

```python
import stomp

list_of_endpoints = [
    ("broker1.mydomain.com", 61614),
    ("broker2.mydomain.com", 61614)
]

connection = stomp.Connection(
    list_of_endpoints,
    use_ssl=True
)

connection.start()
connection.connect(
    "username",
    "password",
    wait=True
)
```

**Expected Behavior**

1. A connection to broker1 is attempted, if this happens to a working node that's great if not, then
1. A connection to broker2 is attempted

**Actual behavior**

1. A connection to broker 1 is attempted, that succeeds on the Socket/TCP-Level as the Load Balancer is available, but the backend isn't (broker2 is currently the primary)
1. I get this exception:
```
[INFO]	2019-09-27T10:10:04.113Z	Attempting connection to host broker1.mydomain.com, port 61614

[INFO]	2019-09-27T10:10:04.274Z	Established connection to host broker1.mydomain.com, port 61614

[INFO]	2019-09-27T10:10:04.292Z	Starting receiver loop
									
[INFO]	2019-09-27T10:10:04.292Z	Sending frame: 'STOMP'
									
[INFO]	2019-09-27T10:10:09.343Z	Receiver loop ended

[ERROR] ConnectFailedException
Traceback (most recent call last):
  File "/var/task/code/lambda_functions/LambdaBase.py", line 8, in handler
    return cls(*args, **kwargs).handle(event, context)
  File "/var/task/code/lambda_functions/mymodule/handler.py", line 51, in handle
    wait=True
  File "/opt/python/stomp/connect.py", line 174, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/opt/python/stomp/protocol.py", line 338, in connect
    self.transport.wait_for_connection()
  File "/opt/python/stomp/transport.py", line 329, in wait_for_connection
    raise exception.ConnectFailedException()
```

**My guess**

There is an underlying assumption, that Message Brokers that aren't (fully) functional won't accept TCP Connections - this doesn't work if there is a Load Balancer in front of a semi-functional Message Broker.

**Comment by rodrigues882013** [comment]
I had the same issue although I wasn't use a NLB. Was there any progress about it?

**Comment by MauriceBrg** [comment]
In my case I'm just using the `broker.mydomain.com` which points to the load balancer. This has the drawback, that a failover takes some time (i.e. a few more seconds than necessary).

**Comment by jasonrbriggs** [comment]
Is this HAProxy as the load balancer.  If you could provide a docker file and haproxy config that demonstrates the problem that might be a step forward in fixing it? (see here for a working example: https://github.com/jasonrbriggs/stomp.py/tree/py2-decom/docker)

**Comment by MauriceBrg** [comment]
It's not an HAProxy but an internal AWS Load Balancer called [Network Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html). AWS doesn't disclose how that's implemented under the hood, but it's most likely not HAProxy. 

I haven't yet worked with HAProxy, but if I have some time next week I might try to set up a test configuration.

**Comment by madkote** [comment]
@jasonrbriggs @MauriceBrg +1 -> same issue with activemq cluster running in kubernetes:
when master switches, library does not reconnect to new master...

I use v4.x.x of stomp.py

**Comment by jasonrbriggs** [comment]
Closing, without a reproducible test case, this won't be resolved.
