### ISSUE TITLE
Documentation includes calls to conn.start() but start() is marked as deprecated

### ISSUE THREAD

**Issue by huntermassey** [jasonrbriggs/stomp.py#257]
Per title, the README and documentation includes calls to start() after creating a connection, but it appears that start() is no longer required and is marked as deprecated.

**Comment by AaronDMarasco** [comment]
If you want SSL or TLS handshaking, I'm pretty sure `start()` is required at the transport level - see #259. Without it, I couldn't get my stuff to connect.

**Comment by jasonrbriggs** [comment]
@AaronDMarasco start/stop in the transport still exists, but on the connection it isn't required.

@huntermassey to be fixed in version 4.2.0 (releasing in the new year)
