### ISSUE TITLE
Heartbeat listener does not exit when connection is closed

### ISSUE THREAD

**Issue by seepa** [jasonrbriggs/stomp.py#26]
Hi,

when closing a StompConnection11 via the `disconnect()` method, the heartbeat listener keeps on running and periodically calls `on_heartbeat_timeout()`.

I was wondering if the expected behavior should be the heartbeat listener closing as well when the connections gets terminated via `disconnect()`.

Adding this to the heartbeat listener class solves this:

```
def on_disconnected(self):
    self.running = False
```
Am I missing something? I also noticed that the attribute `self.running` is currently never set to `False` by anyone...

Best regards,
Patrick

**Comment by jasonrbriggs** [comment]
Don't think you're missing anything. Seems like a bug...

**Comment by jasonrbriggs** [comment]
BTW, will be fixed in the next release.

**Comment by jasonrbriggs** [comment]
Fixed in 4.0.14
