### ISSUE TITLE
Support STOMP connection over SockJS

### ISSUE THREAD

**Issue by charyorde** [jasonrbriggs/stomp.py#27]
Can you support STOMP over websocket with SockJS Implementation as fallback option? Here's the SockJS protocol specs, https://github.com/sockjs/sockjs-protocol

**Comment by jasonrbriggs** [comment]
Sorry, but not something I'd personally be interested in supporting (as in I don't have a need for it myself - nor the time to implement).  But your question did prompt me to finally commit some refactoring I did a while ago on the transport class (to split out the generic transport functionality from the socket-specific implementation).  Which would (hopefully) make it simpler to implement a different transport mechanism.  Branch is here, if of interest at all:
https://github.com/jasonrbriggs/stomp.py/tree/transport-refactor

Will be merged into the master, the next time I have some bug fixes to commit.
