### ISSUE TITLE
current_host_and_port should be accessible before calling connect() method

### ISSUE THREAD

**Issue by nayangoswami-liquidnet** [jasonrbriggs/stomp.py#270]
Suppose I have two activemq servers with different username and password. In order to supply login and password dynamically I want to know, to which server and port the connection was successful while calling  stomp.Connection.

**Comment by jasonrbriggs** [comment]
That sounds like two connections -- something that the client code should be managing, not stomp.py.

**Comment by nayangoswami-liquidnet** [comment]
if I write stomp.Connection([('url1',61613),('url2',61613)]) and now when I want to call connect method with login and passcode, for which url I should supply the details if  I don't know that, with which url the connection is successful. I hope I'm making sense and not doing any silly mistake.

**Comment by jasonrbriggs** [comment]
Stomp doesn't support different credentials with load balanced servers. The assumption is that load balanced servers would have the same credentials.  If you have different credentials with each server then you'll have to manage that as two distinct stomp.Connection requests in your client code.

**Comment by nayangoswami-liquidnet** [comment]
Got the idea. I will try to manage client side. 
One thing to add is,
I'm not sure if the library should have current_host_and_port set before calling connect method. This may be possible or might make sense as document says following for Connection method:
 **"The general idea with the list is to try each address until a successful socket connection is established (giving the ability to provide multiple brokers for failover)."**

**Comment by jasonrbriggs** [comment]
Well the host and port are part of the constructor args (as a list of tuples):
http://jasonrbriggs.github.io/stomp.py/api.html#establishing-a-connection
