### ISSUE TITLE
Minor version change has API breaking changes

### ISSUE THREAD

**Issue by Caligatio** [jasonrbriggs/stomp.py#273]
I've been a happy user of stomp.py for several years but this v4.2 release just cost me time debugging today due to #257.  For future releases, please bump the major version number when breaking API changes are introduced (see https://semver.org/).  Reading #257, the documentation explicitly said to use `.start()` and, although I now see the method comment said it was deprecated, no such warning was emitted using something like a [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning).  Also, while I completely support dropping Python 2 support, this also seems more appropriate for a major version bump than a minor.

Thank you for your continued development of this wonderful module.  I realize the above might come off as harsh but that's only because stomp.py has been a very reliable/excellent part of my project and this caught be unaware.

**Comment by jasonrbriggs** [comment]
Valid point actually.  I decided on version 4.2.0 when I was only planning on the py2 deprecation -- then I kept adding to the release without thinking of the implications of the version.  It doesn't help you now, but I've dumped 4.2.0 (deleted from pypi) and re-release as 5.0.0
