### ISSUE TITLE
Module is logging as 'root' rather than 'stomp.py'

### ISSUE THREAD

**Issue by spurin** [jasonrbriggs/stomp.py#275]
Hi Jason,

Long time user of your module and very much appreciate your work :-)

Have just updated one of our projects to leverage the 5.0.0 release.  Normally, we suppress all stomp.py log messages with the exception of logging.ERROR.  It looks like the logger with a name of 'log' in the 4.x.x release, i.e. -

https://github.com/jasonrbriggs/stomp.py/blob/1b61b10f79fd41476ff0329dbf27f85010d50a8f/stomp/transport.py#L45

That is used for example, here -

https://github.com/jasonrbriggs/stomp.py/blob/1b61b10f79fd41476ff0329dbf27f85010d50a8f/stomp/transport.py#L279

Has been replaced with a call being made, direct to logging -

https://github.com/jasonrbriggs/stomp.py/blob/faf39349a258d4b6b70d944bb16688c6dc6389c7/stomp/transport.py#L274

Unfortunately, this affects our ability to implicitly control the stomp.py log messages.  Do you have a recommended way around this or would you be open to a PR re-implementing this functionality?

Thanks

James

**Comment by jasonrbriggs** [comment]
Well that was a stupid schoolboy error. I forgot that the module logging calls went to the root logger.  Have (I think) fixed that here: https://github.com/jasonrbriggs/stomp.py/pull/276/

Let me know if that works for you and I'll release it asap.

**Comment by spurin** [comment]
Hi Jason,

Appreciate the quick turnaround.  Tested the specific branch this morning with a custom logger and it's looking good -

```
__main__ 01/08/2020 09:49:56 AM Initialising custom StompConnection handler object
__main__ 01/08/2020 09:49:56 AM Calling parent __init__
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Initialising
__main__ 01/08/2020 09:49:56 AM Initialising custom StompConnection handler object
__main__ 01/08/2020 09:49:56 AM Calling parent __init__
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_1: Initialising
__main__ 01/08/2020 09:49:56 AM Initialising custom StompConnection handler object
__main__ 01/08/2020 09:49:56 AM Calling parent __init__
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_2: Initialising
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Preparing connection with host_and_ports - [('hostname.custom.com', 61613)]
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Initialized
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Marking listener object as a listener
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Connection attempt #1
stomp.py 01/08/2020 09:49:56 AM Attempting connection to host hostname.custom.com, port 61613
stomp.py 01/08/2020 09:49:56 AM Established connection to host hostname.custom.com, port 61613
stomp.py 01/08/2020 09:49:56 AM Starting receiver loop
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Connecting
stomp.py 01/08/2020 09:49:56 AM Sending frame: [b'STOMP', b'\n', b'accept-version:1.1\n', b'client-id:message_sender\n', b'\n', b'\x00']
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_1: Preparing connection with host_and_ports - [('hostname.custom.com', 61613)]
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_1: Initialized
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_1: Marking listener object as a listener
custom.corp.stomp.connection 01/08/2020 09:49:56 AM stomp_connection_1: Connection attempt #1
stomp.py 01/08/2020 09:49:56 AM Attempting connection to host hostname.custom.com, port 61613
stomp.py 01/08/2020 09:49:56 AM Received frame: 'CONNECTED', headers={'server': 'ActiveMQ/5.15.1', 'session': 'message_sender', 'version': '1.1', 'heart-beat': '0,0'}, body=''
custom.corp.stomp.connection 01/08/2020 09:49:56 AM message_sender: Connected
stomp.py 01/08/2020 09:49:56 AM Established connection to host hostname.custom.com, port 61613
stomp.py 01/08/2020 09:49:56 AM Starting receiver loop
```

Noticed that the version when installed was still 5.0.0 but that aside, it's looking great.

Thank you

- James

**Comment by jasonrbriggs** [comment]
5.0.1 released (https://pypi.org/project/stomp.py/)
