### ISSUE TITLE
link to download stomp.py version 3.0+ is broken

### ISSUE THREAD

**Issue by noap** [jasonrbriggs/stomp.py#28]
Hi,

It looks like the link to download version 3.0+ for Python2.x and Python3.x is broken - it directs to https://code.google.com/hosting/moved?project=stomppy, indicating it is no longer being hosted on code.google.com. Is there any way to download stomp.py for STOMP 1.1? I'm specifically looking for version 3.1.3.

Thanks!
Noa

**Comment by jasonrbriggs** [comment]
Whoops.  Try this one: https://pypi.python.org/pypi/stomp.py/3.1.3

The latest version does support STOMP 1.1 by the way...
