### ISSUE TITLE
Connection.disconnect() hangs

### ISSUE THREAD

**Issue by andy-maier** [jasonrbriggs/stomp.py#284]
We are still supporting Python 2.7 and therefore have to use stomp.py version 4.1.22. That version works very fine, except that some of our users saw that `Connection.disconnect()` hangs for them. See our issue https://github.com/zhmcclient/python-zhmcclient/issues/572 for details.

We debugged the problem and found that stomp.py PR #266 actually contains a fix for it. PR #266 is a monster PR with 66 commits, so what we found is we need just a few lines from commit #3ceb127 of PR #266. We verified that the fix works for us. The fix is the last commit in branch https://github.com/andy-maier/stomp.py/tree/andy/fix-disconnect-hang, but because there is no branch for 4.1 I cannot create a PR for it.

Could you please consider picking up that fix into 4.1 and releasing a 4.1.23 ?

**Comment by jasonrbriggs** [comment]
4.1.23 released with your changes:

https://github.com/jasonrbriggs/stomp.py/compare/v4.1.22...v4.1.23

Hope that works for you.

**Comment by andy-maier** [comment]
Hi Jason. Wow! So quickly! Thanks very much for this!
