### ISSUE TITLE
stomp.py v5.0.0 and v5.0.1 not on pypi

### ISSUE THREAD

**Issue by choilive** [jasonrbriggs/stomp.py#288]
Aforementioned versions no longer seem available on pypi, is there a reason for that? They seemed to be available not too long ago.

EDIT: forgot to mention that I have requirements that explicity set the package version to them. Brought to my attention since our automated builds were failing b/c that package is no longer available.

**Comment by pshchelo** [comment]
@choilive https://github.com/jasonrbriggs/stomp.py/issues/279#issuecomment-586623165

**Comment by jasonrbriggs** [comment]
@pshchelo is correct - basically yanked those releases because they were causing problems after removing py2 compatibility.  Changelog updated now to reflect the same: https://github.com/jasonrbriggs/stomp.py/blob/dev/CHANGELOG.md
