### ISSUE TITLE
Remove traceback.print_stack() in protocol.py

### ISSUE THREAD

**Issue by spurin** [jasonrbriggs/stomp.py#291]
Hi Jason,

Have tested version 6.0.0 of stomp.py, thanks again for the efforts.  It's working well, but, we are seeing a lot of stack traces where we are overcautious on the disconnect.  Is this intentional or should this be removed?

Raised the following PR -

https://github.com/jasonrbriggs/stomp.py/pull/290

Have based this on the logic that the debug message, would satisfy this scenario as per previous versions.

Thanks

James Spurin

**Comment by jasonrbriggs** [comment]
Left that in by mistake after diagnosing another issue. Thx for the PR.
