### ISSUE TITLE
Version 5 of stomp is gone

### ISSUE THREAD

**Issue by krav4** [jasonrbriggs/stomp.py#292]
Where did the version 5.0.1 go? Pypi does not have and release history on documentation page does not have it: [https://pypi.org/project/stomp.py/#history](url)

EDIT: using python 3.7,  pip version 19.3.1

**Comment by krav4** [comment]
Ok it has been yanked, not sure why but i will close the issue

**Comment by jasonrbriggs** [comment]
https://github.com/jasonrbriggs/stomp.py/blob/dev/CHANGELOG.md
