### ISSUE TITLE
Can't pip install

### ISSUE THREAD

**Issue by alexpdp7** [jasonrbriggs/stomp.py#30]
$ python --version
Python 2.7.8
$ pip --version
pip 1.5.6 from /home/acorcoles/.virtualenvs/scratch/local/lib/python2.7/site-packages (python 2.7)
$ pip install -i https://pypi.python.org/simple stomp.py
Downloading/unpacking stomp.py
  Using download cache from /home/acorcoles/.cache/pip/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fs%2Fstomp.py%2Fstomp.py-4.0.15.tar.gz
  Running setup.py (path:/tmp/pip-build-pEcKl1/stomp.py/setup.py) egg_info for package stomp.py
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-pEcKl1/stomp.py/setup.py", line 12, in <module>
        import stomp
      File "stomp/__init__.py", line 12, in <module>
        import stomp.connect as connect, stomp.listener as listener
      File "stomp/connect.py", line 1, in <module>
        from stomp.transport import *
      File "stomp/transport.py", line 25, in <module>
        DEFAULT_SSL_VERSION = ssl.PROTOCOL_SSLv3
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-pEcKl1/stomp.py/setup.py", line 12, in <module>

    import stomp

  File "stomp/__init__.py", line 12, in <module>

    import stomp.connect as connect, stomp.listener as listener

  File "stomp/connect.py", line 1, in <module>

    from stomp.transport import *

  File "stomp/transport.py", line 25, in <module>

    DEFAULT_SSL_VERSION = ssl.PROTOCOL_SSLv3

AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-pEcKl1/stomp.py
Storing debug log for failure in /home/acorcoles/.pip/pip.log

**Comment by jasonrbriggs** [comment]
Works for me with python2.7:

'''
$ python --version
Python 2.7.9
$ pip --version
pip 6.0.8 from /Users/jasonbriggs/misc/environments/tmp/lib/python2.7/site-packages (python 2.7)
$ pip install stomp.py
Collecting stomp.py
  Using cached stomp.py-4.0.15.tar.gz
Installing collected packages: stomp.py
  Running setup.py install for stomp.py
    changing mode of build/scripts-2.7/stomp from 644 to 755
    changing mode of /Users/jasonbriggs/misc/environments/tmp/bin/stomp to 755
Successfully installed stomp.py-4.0.15
'''

Maybe the version of ssl you have installed is the problem?  

I'm thinking the only thing I can do here, is catch the attribute error and then disable SSL in that situation.

**Comment by alexpdp7** [comment]
Hmmm, didn't look much closely at this and just fired a bug away.

Upon closer inspection, SSLv3 shouldn't really be used (e.g. from http://en.wikipedia.org/wiki/Transport_Layer_Security#SSL_1.0.2C_2.0_and_3.0 ,:

As of 2014 the 3.0 version of SSL is considered insecure as it is vulnerable to the POODLE attack that affects all block ciphers in SSL; and RC4, the only non-block cipher supported by SSL 3.0, is also feasibly broken as used in SSL 3.0.

). I believe SSLv3 support is being removed from many places. Probably stomp.py should not default to it.

**Comment by jasonrbriggs** [comment]
Good point.  Forgot about POODLE.  I've set the default to TLSv1, and if that doesn't exist it will disable ssl support.

**Comment by alexpdp7** [comment]
I can confirm 4.0.16 installs fine, thanks
