### ISSUE TITLE
on_before_message affecting message to all listeners

### ISSUE THREAD

**Issue by fabiohk** [jasonrbriggs/stomp.py#300]
I'm not sure if this is the correct approach nor if it's the desirable behaviour, but I noticed that if I have two listeners attached to the same transport and one of them change the `headers` or `body` inside the `on_before_message` method, all the subsequent listeners will received the modified message.

Is this the desired behaviour or am I missing something?

**Comment by jasonrbriggs** [comment]
Yes, the stomp frame is an object -- and not intended to be unmodifiable -- so changing it in one listener would affect the next.

**Comment by fabiohk** [comment]
Ok, but then with that listeners interdependency, we can’t establish two, or more, lines of execution in a simple manner.

Why have it? Is there any advantage in that approach?

**Comment by jasonrbriggs** [comment]
The advantage is you can use a chain of listeners to enrich the message with further detail (i.e. pre/post processing steps).  I recall at least one conversation with a user who is doing something along those lines. Ideally both usecases should be possible.  A version of the frame which is the modified version versus the original -- but obviously it hasn't be raised before.

**Comment by jasonrbriggs** [comment]
Closing issue since this will be addressed in the next release.
