### ISSUE TITLE
"keepalive=True" not effective in MacOS and Windows 10.

### ISSUE THREAD

**Issue by imaxwen** [jasonrbriggs/stomp.py#301]
Source Code:
```python
conn = stomp.Connection12(host_and_ports=[('127.0.0.1', 8083)],vhost='/',keepalive=True)
conn.set_listener('listener', MyListener(conn))
conn.connect(username='guest', passcode='guest', wait=True)
conn.subscribe(destination='/queue/integer-addition', id="1688", ack='auto')
```

The connect always closed automatically,  Please help :)

**Comment by jasonrbriggs** [comment]
keepalive was never implemented for anything other than linux.  I have a proposed macos implementation (https://github.com/jasonrbriggs/stomp.py/pull/303) but currently no mac test environment setup to validate whether it works or not.  In terms of Windows, I have even less enthusiasm to figure it out...

**Comment by jasonrbriggs** [comment]
Added for mac as of the next release.  Windows won't be implemented (as discussed in earlier comment).
