### ISSUE TITLE
Custom transport implementation

### ISSUE THREAD

**Issue by aragaer** [jasonrbriggs/stomp.py#307]
From STOMP spec:

> STOMP is a frame based protocol which assumes a reliable 2-way streaming network protocol (such as TCP) underneath.

In my project I'm using a custom transport (shell over ssh connection). I had to reverse the BaseTransport class in order to create my own transport. I then had to create a custom Connection class to use that transport. It would be easier if the Transport class interface was documented and Connection class was accepting an instance of a Transport implementation.

**Comment by jasonrbriggs** [comment]
@aragaer Isn't the Transport closely tied to the Connection anyway?  For example, [multicast.py](https://github.com/jasonrbriggs/stomp.py/blob/dev/stomp/adapter/multicast.py), has a custom transport and custom connection -- even if I change the Connection to take a transport (and create one if none is provided), wondering if that's really going to be that useful for people implementing their own transports?

**Comment by aragaer** [comment]
Custom transport is exactly what I had to do [here](https://github.com/yet-another-personal-assistant/stomp-over-ssh/blob/master/sshstomp/__init__.py). I'm not saying that's the most correct way of doing what I wanted, just the one that was most obvious one for me.
