### ISSUE TITLE
NACK command is not working in ActiveMQ/Artemis

### ISSUE THREAD

**Issue by rtista** [jasonrbriggs/stomp.py#315]
I am unsure if this might be related to the STOMP implementation or the brokers but the NACK command does not seem to work under ActiveMQ or ActiveMQ Artemis, I've tested with both these brokers and both STOMP 1.1 and 1.2 connections.

I've been using a listener with a prefetch size of 10 which places messages in an in-memory queue which are immediately consumed by a process which nack's them, yet for some reason, all the messages are being acknowledged when what should be happening is similar to a "Poison Pill" scenario where these messages should be making the consumer loop infinitely over the same 20 messages.

I am aware that ActiveMQ Artemis does not support transactional acknowledgments, and so I am not using any. I would mostly like to know if anybody is able to test this and check if they have the same problem?!

Below lies the test code I've using:

```python
import contextlib
import stomp
import queue
import os


SUBSCRIPTION_HEADERS = {
    'subscription-type': 'ANYCAST',
    'consumer.prefetchSize': 10
}


class MyListener(stomp.ConnectionListener):
    """
    Retrieves messages and places them on queue.

    Args:
        stomp.ConnectionListener (class): Connection listener.
    """
    def __init__(self, conn, queue):
        self.conn = conn
        self.queue = queue

    def on_error(self, headers, message):
        print('received an error "%s"' % message)

    def on_message(self, headers, message):
        self.queue.put((headers, message))

    def on_send(self, frame):
        print(f'{frame}')

    def on_disconnected(self):
        print('disconnected')
        conn.connect(wait=True, headers={'client-id': os.getpid()})
        conn.subscribe(destination='delivery-logs', id=1, ack='client', headers=SUBSCRIPTION_HEADERS)

# 
# Main execution flow
# 

# In-memory message queue 
messageq = queue.Queue(maxsize=10)

# Create stomp connection and connect
conn = stomp.Connection11([('localhost', 61613)], heartbeats=(5000, 5000))
conn.connect(wait=True, headers={'client-id': 123})

# Send 10 messages into the queue
for i in range(10):
    conn.send(
        'test', 'Hello World', persistent=True, priority=1, 
        headers={
            'destination-type': 'ANYCAST',
            'durable': 'true'
        })

# Set connection listener
conn.set_listener('QueueListener', MyListener(conn, messageq))

# Subscribe to the queue as 'client-individual'
conn.subscribe(
    destination='test', id=123, ack='client-individual',
    headers=SUBSCRIPTION_HEADERS
)

count = 0

while True:

    with contextlib.suppress(queue.Empty):

        # Retrieve message
        headers, body = messageq.get(True, 10)

        # Consume message
        count += 1

        # Acknowledge message consumption
        conn.nack(headers['message-id'], 123)

        continue

    break

print(f'Consumed {count} messages')

# Unsubcribe and disconnect
conn.unsubscribe(123)
conn.disconnect()
```

**Comment by jasonrbriggs** [comment]
> yet for some reason, all the messages are being acknowledged when what should be happening is similar to a "Poison Pill" scenario where these messages should be making the consumer loop infinitely over the same 20 messages.

Are you sure that's the correct behaviour in this scenario? From the stomp spec:

> NACK is the opposite of ACK. It is used to tell the server that the client did not consume the message. The server can then either send the message to a different client, discard it, or put it in a dead letter queue. The exact behavior is server specific.

Surely it should either be throwing the message into the DLQ or delivering to another consumer? So you wouldn't get an infinite reprocessing of the same messages...

**Comment by rtista** [comment]
Yep, it must be a server behavior which I was unaware of, thank you for the quick a concise explanation Jason! ;) Closing! :+1:
