### ISSUE TITLE
Stacktrace when one of the AMQ instance is not accessible (exc_info=1)

### ISSUE THREAD

**Issue by gregoan** [jasonrbriggs/stomp.py#316]
Hi,

We are using multiple AMQ instances so multiple tuple elements are used when stomp.Connection12 constructor is called
If the first element is not accessible (Active/Passive architecture), the second one will be used but we got stacktrace due to the fact  the first one is not accessible and it's very confusing from my point of view.

> 'Traceback (most recent call last):'
>   '  File "/ec/local/automation/home/tauamaq/.local/lib/python3.7/site-packages/stomp/transport.py", line 727, in attempt_connection'
>   '    self.socket = socket.create_connection(host_and_port, self.__timeout)'
>   '  File "/ec/local/automation/deploy/ansible/amazonmq/python/lib/python3.7/socket.py", line 728, in create_connection'
>   '    raise err'
>   '  File "/ec/local/automation/deploy/ansible/amazonmq/python/lib/python3.7/socket.py", line 716, in create_connection'
>   '    sock.connect(sa)'

We noticed the stacktrace is raised due to "exc_info=1" in transport.py (line 784):
`logging.warning("Could not connect to host %s, port %s", host_and_port[0], host_and_port[1], exc_info=1)`

Could you please let me know why you print the stacktrace (The Warning statement should be enough to indicate the instance  XYZ is not accessible no ?)
Will it be possible to avoid it (optional parameter to show stacktrace) ?

Regards,
GREGOIRE Alain.

**Comment by jasonrbriggs** [comment]
I don't recall now why the stacktrace is logged.  I think it's reasonable to switch it off by default, and allow the old behaviour to be re-enabled with a flag.  Fixed with this PR: https://github.com/jasonrbriggs/stomp.py/pull/317, and available in version 6.1.0.

**Comment by gregoan** [comment]
Hi,

Thank you so much.

Regards.

Le dim. 12 juil. 2020 à 11:48, jasonrbriggs <notifications@github.com> a
écrit :
