### ISSUE TITLE
Not receiving the same sized data stream as what was sent

### ISSUE THREAD

**Issue by rlkcpo** [jasonrbriggs/stomp.py#319]
So I wrote a simple script to test stomp.py communicating through an ActiveMQ broker. 
I am trying to send a bytes stream of 184 bytes through the connection:
`self.m_conn.send(body=data, destination="/topic/" + self.m_topic) #len(data) = 184`

What I am receiving on the other end is intermittent sometimes 181 sometimes its 182
`def on_message(self, headers, message):`
`  print(len(message)) #prints 181 or 182`

This only happens when both the producer and consumer of the message is a stomp.py implementation. If I send data from stomp.py to the broker and then to a C++ process it works just fine, and vice versa.

**Comment by jasonrbriggs** [comment]
@rlkcpo Could you add the test script you're using which demonstrates this problem?

**Comment by jasonrbriggs** [comment]
Closing since no more info has been provided.
