### ISSUE TITLE
Client Not Disconnecting As Expected

### ISSUE THREAD

**Issue by blakfeld** [jasonrbriggs/stomp.py#323]
We have a short lived job run by a Lambda function that notifies an internal service about changes on an S3 bucket, and it seems like it's not disconnecting from ActiveMQ as expected. Here is the code:

```python
import json
import stomp
import os


def lambda_handler(event, context):
    print("S3 notif received...")
    s3event = event["Records"][0]["s3"]['object']['key']
    s3event = s3event.rsplit('/',1)[1]
    notify_service(s3event)

    return {
        'statusCode': 200,
        'body': json.dumps('Service notified...')
    }


def notify_service(s3event):
    conn = stomp.Connection([
        (os.environ.get('BROKER_URL_1'), 61614),
        (os.environ.get('BROKER_URL_2'), 61614),
    ], auto_content_length=False, use_ssl=True)

    message = {
        "event":"totally.awesome.thing.updated",
        "message": s3event 
    }

    topic = '/topic/Service'
    conn.connect('service', os.environ.get('BROKER_PW'))
    
    try:
        conn.send(topic, json.dumps(message))
    finally:
        conn.disconnect()
```

But if I watch the ActiveMQ console, the stomp connections remain active until eventually it seems to exhaust all ports available to service them.

We're using Stomp.py version 6.1.0 - any pointers as to what we may be doing wrong here?

**Comment by achaiah** [comment]
It seems like the disconnect() function is broken. I too am encountering issues when trying to disconnect. I have heartbeats set up and even after the disconnect() function returns, stomp.py attempts to send heartbeats through a non-existing connection and generates:
```
BrokenPipeError: [Errno 32] Broken pipe
Error sending frame
```

**Comment by jasonrbriggs** [comment]
@blakfeld Apols for never replying.  I can't see an exact cause for the issue, but wondering if you should have wait=True on connection.  Perhaps sending before the connection is established is enough to cause some weird behaviour?

@achaiah I could see that heartbeating would continue *while* disconnecting, but not sure I see an issue after disconnecting.  Perhaps adding a fix for stopping heartbeating after disconnect has been sent will help, but not sure it will help with your problem.

**Comment by achaiah** [comment]
@jasonrbriggs  Yeah I think whatever thread is sending heartbeats never stops sending them. I would suggest stopping the heartbeating thread on disconnect() or at least setting some flag that would **NOT** send heartbeats but would keep the thread alive until a connection is reestablished.

**Comment by jasonrbriggs** [comment]
I believe this is resolved in the latest version (the heartbeat listener stops sending if transport.is_connected is false, or stomp is disconnecting.

**Comment by amaltaro** [comment]
Hello, is it supposed to have been fixed in stomp.py version `7.0.0`?
I am using this version to post data to AMQ and noticed that the component is accumulating file descriptors (sockets), eventually hitting the soft kernel limit of 1024 (with an error "Too many open files").
