### ISSUE TITLE
RPC ConnectionListener

### ISSUE THREAD

**Issue by YuvalPeleg** [jasonrbriggs/stomp.py#324]
Hey,
First of all, great job on this project.
Second, I built something that I can probably easily turn into an RPC ConnectionListener over ActiveMQ. Is that a contribution you would like?

Thanks

**Comment by jasonrbriggs** [comment]
Thanks anyway, but that's not the sort of functionality I would generally include because it's not core functionality for a stomp lib.  I'd suggest either forking-and-adding or release it as an add-on library.
