### ISSUE TITLE
ActiveMQ Listener port range

### ISSUE THREAD

**Issue by Kr1shna** [jasonrbriggs/stomp.py#326]
Hi,

I tried to start python script which sends message to queue into AMQ server and listens other queue for response. It works well.
But if I want to run this python script in docker container, I need to open port range for queue listeners. But looks like it's completeley random! (I have tried to catch it many times)

Maybe there is a method or something in stomp.py code when I can set up this range?

**Comment by akessler1ctr** [comment]
This is because stomp.py doesnt let you set the bind port.  That option needs to be added and passed through the connection/transport.  Then you can use the docker to expose the port.

**Comment by jasonrbriggs** [comment]
bind_host_port is available as a constructor param in the latest version.
