### ISSUE TITLE
Update http://jasonrbriggs.github.io/stomp.py/quickstart.html

### ISSUE THREAD

**Issue by svetli-n** [jasonrbriggs/stomp.py#332]
to

```
class MyListener(stomp.ConnectionListener):
    def on_error(self, headers, body):
        print('received an error "%s"' % body)

    def on_message(self, headers, body):
        print('received a message "%s"' % body)
```

**Comment by edison12a** [comment]
It would be better if the documentation page was made public; Open for PRs

**Comment by jasonrbriggs** [comment]
Not sure what you mean.  It is: https://github.com/jasonrbriggs/stomp.py/tree/gh-pages

Also the source docs are here: https://github.com/jasonrbriggs/stomp.py/tree/dev/docs

**Comment by jasonrbriggs** [comment]
(hit close by mistake)
