### ISSUE TITLE
Choose how to handle consequences of a Nack

### ISSUE THREAD

**Issue by simonefrancia** [jasonrbriggs/stomp.py#334]
Hi,
thanks for the project.
I have a question about nacks.
We would like to choose how to manage the consequence of a nack.
After the broker receives the message and calls a callback, we give an output that represents the outcome of a certain operation. 
In the case the outcome is ok, we send an ack to tell the broker that message was consumed correctly: in case the outcome is not ok, we would like to re-queue that message in the original queue adding a sort of counter that counts the number of times the element was re-queued. 
Is correct this behavior and how can we get it?
Thanks

**Comment by the01** [comment]
I think the behavior is broker specific. ActiveMQ for example removes the message if you nack it. However, if you let it timeout without an ack, it will get rescheduled for a configurable number of times until it is moved to the dead letter queue. At least that was what I got with the default config. I might be unaware of some settings that make it behave nicer..
