### ISSUE TITLE
Is listener mandatory for producers?

### ISSUE THREAD

**Issue by kannanF9T** [jasonrbriggs/stomp.py#335]
Hi team,
I have created a three different helpers using stomp.py
######Consumer helper:
Long running consumer classes which process the message in on_message method (heartbeat enabled),
Reconnect implemented in consumer itself
```
 while True:
            time.sleep(5)
            if not self.conn.is_connected():
                  try:
                       self.conn.disconnect()
                       self.create_connection()
                 except stompException:
                        print("exception %s"%ex)
```
######Producer helper:
Singleton class which send the message to activemq and no listeners attached to it (heartbeat enabled and),

```     def send(destinations, body, header):
           if not self.conn.is_connected():
                 self.create_connection()
```

###### RPC helper:
Implemented request and response model using listeners and without heartbeat (30 secs timeout logic for receiving message) and updates the response value in on_message block

My question here is do we need to implement listener for producer helper since it doesn't require any methods in listener except for heartbeats or stomp.py by default adds a listener.

**Comment by jasonrbriggs** [comment]
No the listener isn't mandatory.  The producer doesn't have to subscribe to events (send and receipt are separate "loops" for want of a better word).  The producer can be fire-and-forget without any issues from my perspective...

**Comment by kannanF9T** [comment]
Is it good to implement producer as singleton (singleton stomp connection for producer) with heartbeat enabled and reconnect mechanism during send by checking 
```connection.is_connected()```

with this we are trying to reduce the connection creation time
