### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by mtmcgrew** [jasonrbriggs/stomp.py#34]
This does not support ipv6 addresses.

**Comment by jasonrbriggs** [comment]
I think probably supportable by just changing `socket.socket` and `socket.connect` to `create_connection`... but not something I can easily test if it works (given last time I tried to get a python client to connect to my test server with ipv6 it failed miserably, and no luck finding any help on the web for the error message).

Will look at implementing anyway, and perhaps someone else can report back whether it works or not...

**Comment by maus-** [comment]
@jasonrbriggs will happily test the changes, let me know when you have it ready

**Comment by jasonrbriggs** [comment]
@maus- Implemented in branch: https://github.com/jasonrbriggs/stomp.py/tree/ipv6-support (only a minor change really).  Actually I've managed to test it myself after all -- just needed the correct voodoo.  But would still be good to see if it works successfully for someone else...
