### ISSUE TITLE
Multiple subscriptions

### ISSUE THREAD

**Issue by the01** [jasonrbriggs/stomp.py#340]
Is it designed to have multiple subscriptions (e.g queue1 and queue2) on one connection?

In my tests I subscribe to queue1 and then queue2 and split my messages evenly between both.
What I then see, is that it will continuously receive the message for queue2 and every x seconds (~1 minute/~30 msgs) a bulk for queue1 (or the other way around).
This mostly happens when there are plenty of messages in the queue.

Is this intended? I would have expected that it takes one messages from queue1 and one from queue2.
Or is this an ActiveMQ issue entirely?

**Comment by kannanF9T** [comment]
Please try to set "activemq.prefetchSize":1 in subscribe method
headers={"activemq.prefetchSize":1}

**Comment by the01** [comment]
Ah, I had this for commented out for some reason. But works now, thank you!
