### ISSUE TITLE
WebSocket Stomp Client implementation

### ISSUE THREAD

**Issue by ppratheesh** [jasonrbriggs/stomp.py#342]
Hi all,
   I am checking a solution for connecting my stomp python client to my rabbitmq  broker through a WebSocket endpoint.But i couldn't  figure out how to specify  the path "/ws" where my rabbitmq WebSocket endpoint is available.
Is there any method available for specifying the path ??

**Comment by jasonrbriggs** [comment]
No there's no method because stomp.py doesn't support websocket connections.
