### ISSUE TITLE
6.1.0 package contains older code?

### ISSUE THREAD

**Issue by bgardner8008** [jasonrbriggs/stomp.py#350]
I was trying to debug the reconnection issue and installed package directly from github, tag v6.1.0. Then my app got exceptions that my on_message handler was missing positional argument. In commit 6314faeb notify was changed to pass the frame object rather than separate headers and body, and my code was expecting two arguments. But wait, my code is already running using stomp.py==6.1.0 in requirements. I downloaded stomp.py-6.1.0-py3-none-any.whl and looked at the code and it is missing this change, so it appears the code in the 6.1.0 package is older than tag v6.1.0.

**Comment by stadelmanma** [comment]
@jasonrbriggs and @bgardner8008  I can also confirm this behavior. However, the changes on https://github.com/jasonrbriggs/stomp.py/blob/v6.1.0/stomp/transport.py#L244 break backwards compatibility with 6.0.0 for the listener functions at least, I didn't do a full diff.

I wonder if that tag actually contains _newer_ code than intended and what is on PyPI is correct?

**Comment by bgardner8008** [comment]
Right, I'm not sure it's "older", but it is different. My assumption was that the package on PyPI is from an earlier commit, and doesn't include PR #309 so as not to break backward compatibility. But I didn't try to figure out which commit, and I currently lack the motivation to track it down further. In my own work I've stopped using my fork with added debugging and rolled back to using the 6.1.0 package from PyPI, whatever commit that is from.

**Comment by jasonrbriggs** [comment]
Don't quite know how that happened, but I've released the latest version (6.1.1) and re-tagged -- and double-checked pypi is exactly the same as the tagged code.

**Comment by bgardner8008** [comment]
Thanks. If/when I get back to my stomp project I will update to 6.1.1.

**Comment by jasonrbriggs** [comment]
@bgardner8008 Perhaps hold off updating to 6.1.1.  It was pointed out [here](https://github.com/jasonrbriggs/stomp.py/issues/352) that 6.1.1 (actually 6.1.0) has an incompatible api change, so I'm going to yank 6.1.0 and 6.1.1 and re-release 7.0.0 to reflect that. It's only a version number diff in the end but at least it makes it clear the api has changed.
