### ISSUE TITLE
stomp.py 6.1.1 breaks implementers of ConnectionListener class

### ISSUE THREAD

**Issue by andy-maier** [jasonrbriggs/stomp.py#352]
Hi,
we found that stomp.py 6.1.1 changed its interface incompatibly compared to version 6.1.0 on Pypi.

PR #309 changed `ConnectionListener.on_message()` from:
```
def on_message(self, headers, body):
```
to:
```
def on_message(self, frame):
```
as well as several other `ConnectionListener` methods similarly.

This breaks user code that implements these methods:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 346, in __receiver_loop
    self.process_frame(f, frame)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 193, in process_frame
    self.notify(frame_type, f)
  File "/usr/local/lib/python3.6/dist-packages/stomp/transport.py", line 246, in notify
    notify_func(frame)
TypeError: on_message() missing 1 required positional argument: 'message'
```

See for example https://github.com/zhmcclient/python-zhmcclient/issues/763

**Comment by jasonrbriggs** [comment]
The original intent was to roll the version forward to 7.0.0 to correctly reflect the incompatibility (as per here: https://github.com/jasonrbriggs/stomp.py/pull/309/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R3) but somehow I managed to forget and reverted the version update.

I think I'll yank versions 6.1.0 and 6.1.1 and release version 7, which at least highlights the diff.

**Comment by andy-maier** [comment]
Hi Jason. I think that would be the right approach. Thanks!

For now, we'll pin stompy.py to <7.0.0,!=6.1.0,!=6.1.1 until we get to using the new interface.
