### ISSUE TITLE
6.1.0 on Pypi is different from v6.1.0 tagged version in the repo

### ISSUE THREAD

**Issue by andy-maier** [jasonrbriggs/stomp.py#353]
Related to #352 I just opened:

I was wondering why the PR that introduced the incompatibility was merged between repo tags v6.0.0 and v6.1.0, yet the 6.1.0 version from Pypi was not yet incompatible.

Commit history of dev branch in repo, back to tag v6.1.0:
```
021ca95 (HEAD -> dev, tag: v6.1.1, origin/dev, origin/HEAD) fix version in poetry file
8f0d616 fix version
... (17 commits not shown)
4a646e0 minor update to changelog
a2e0fb4 (tag: v6.1.0) fix version in pyproject
314b192 update changelog for release
... (25 commits not shown)
eba178b pass frame as argument to listener funcs
6314fae change notify to pass in the frame                              <---------- commit that broke compatibility
1521e1c Merge pull request #306 from jasonrbriggs/minor-makefile-fix.   <---------- 6.1.0 version on Pypi???
9c24b95 update version, fix makefile
... (22 commits not shown)
0dc1f99 update version for next release
f2832ab (tag: v6.0.0) changelog update
```

It turns out that the code in the stomp directory of version 6.1.0 on Pypi is equal to this commit:

```
1521e1c Merge pull request #306 from jasonrbriggs/minor-makefile-fix
```
which is somewhere in the middle between v6.0.0 and v6.1.0 of the repo (and before the change that broke compatibility).

**Comment by jasonrbriggs** [comment]
Yes that was already raised here: https://github.com/jasonrbriggs/stomp.py/issues/350, which was why 6.1.1 was raised to address (and get the latest version in pypi consistent with the release tag).  But re your point on issue 352, 6.1.* introduces a backwards incompatible api change so it makes more sense to yank those two versions and re-release version 7.0.0.  Which I'll do tomorrow.
