### ISSUE TITLE
Support pyopenssl 21

### ISSUE THREAD

**Issue by traylenator** [jasonrbriggs/stomp.py#371]
With the new 8 release the optional  requirement on pyopenssl is

```
PyOpenSSL = {version = "^20.0.1", optional = true}
```

that resolves to `<21`  so the new version 22

https://pypi.org/project/pyOpenSSL/

is not supported ?

Can the requirement be relaxed?

**Comment by traylenator** [comment]
https://www.pyopenssl.org/en/stable/changelog.html
changelog looks okay at least.

**Comment by jasonrbriggs** [comment]
Note: Have removed PyOpenSSL altogether and moved to the latest cryptography module version (37.0.1).  See version 8.0.1: https://pypi.org/project/stomp.py/8.0.1/
