### ISSUE TITLE
artemis download is a 404 when building Docker image

### ISSUE THREAD

**Issue by ghost** [jasonrbriggs/stomp.py#379]
http://www.apache.org/dist/activemq/activemq-artemis/2.20.0/apache-artemis-2.20.0-bin.tar.gz is now a 404

It could be https://downloads.apache.org/activemq/activemq-artemis/2.22.0/apache-artemis-2.22.0-bin.tar.gz that is needed, in which case, the Dockerfile also needs a change as that is version 2.22 and not 2.20:

```
-RUN apache-artemis-2.20.0/bin/artemis create testbroker --user testuser --password password --allow-anonymous --no-amqp-acceptor --no-hornetq-acceptor --default-port 61619
+RUN apache-artemis-2.22.0/bin/artemis create testbroker --user testuser --password password --allow-anonymous --no-amqp-acceptor --no-hornetq-acceptor --default-port 61619
```

**Comment by jasonrbriggs** [comment]
Fixed on dev branch.
