### ISSUE TITLE
Documentation ?

### ISSUE THREAD

**Issue by JulienPalard** [jasonrbriggs/stomp.py#38]
Hello,

I'm new to stomp, and stomp.py, I tried the demo, and received a message I previously posted using curl and the rest endpoint, great. Now I'm searching for some documentation, typically about the subscribe method, I found the "API Documentation" listing classes methods and parameters name, but I can't find a documentation about "what does what", typically the `ack` parameter, where do I find what are the different possible values for it ?

If this kind of documentation exists, I think it may be cool to link to it from the README,
Bests.

**Comment by jasonrbriggs** [comment]
If you're looking for info about what the different methods and parameters do, here's probably a good place:
https://stomp.github.io/stomp-specification-1.2.html

Stomp.py should hopefully be pretty close to the protocol.
