### ISSUE TITLE
Activemq queue length via stomp.py

### ISSUE THREAD

**Issue by marc-philipp-knechtle** [jasonrbriggs/stomp.py#385]
Hi, I tested your example scripts and it works wonderfully to send and receive messages. 

But I wondered whether it's possible to make meta information requests about queues. Im particularly interested in the size of the queues. (Without readming the messages as I have another message-consumer)

Sadly I did not find any options to do this in the documentation. 

Thanks a lot in advance!

**Comment by jasonrbriggs** [comment]
This isn't functionality that stomp.py would provide.  If anything it would be something the message broker/server would provide via a rest api or some similar mechanism.
