### ISSUE TITLE
asyncio support

### ISSUE THREAD

**Issue by grigi** [jasonrbriggs/stomp.py#39]
Hi

How easy would it be to use stomp.py in an asyncio framework? 

As I understand it, currently stomp.py handles async-ness using a connection listener in a separate thread, one needs to do some synchronisation between the different threads.
coroutines work simply because they avoid the need for synchronisation, and I'm unsure how an on_message() would be able to insert something into the event-loop in a safe way.

Any ideas? It might be useful to look at something like aoizmq? Am I approaching this wrong?

Regards

**Comment by jasonrbriggs** [comment]
Haven't really looked much into asyncio to be honest, so I'm afraid no real idea. Seems like something that would require a reasonable chunk of rewriting to support.

**Comment by dejlek** [comment]
Yes, it will require huge amount of work. However, there will be a considerable performance gain as well.

**Comment by nboxall** [comment]
Hi,

I was wondering if this thread has lead to any future plans for stomp.py to support asyncio?

Thanks

**Comment by wklm** [comment]
any updates?

**Comment by jasonrbriggs** [comment]
No updates. Unless I win the lottery and wind up with masses of spare time, no personal interest in rewriting to support asyncio.
