### ISSUE TITLE
try_setsockopt() usage in transport.py broken on Mac 

### ISSUE THREAD

**Issue by PalNilsson** [jasonrbriggs/stomp.py#391]
Hi,

On Macs, this

            if try_setsockopt(self.socket, "enable", SOL_SOCKET, SO_KEEPALIVE, 1):
                try_setsockopt(self.socket, socket.IPPROTO_TCP, 0x10, ka_intvl)

leads to the error

try_setsockopt() missing 1 required positional argument: 'val'

Can you please check?

Regards, Paul

**Comment by zkan** [comment]
This happened to me too. Right now I work around by changing this code here: https://github.com/jasonrbriggs/stomp.py/blob/dev/stomp/transport.py#L661 from

```py
    def __enable_keepalive(self):
        def try_setsockopt(sock, name, fam, opt, val):
            if val is None:
                return True  # no value to set always works
```

to

```py
    def __enable_keepalive(self):
        def try_setsockopt(sock, name, fam, opt, val=None):
            if val is None:
                return True  # no value to set always works
```

**Comment by jasonrbriggs** [comment]
Made that change for the next version.  I don't have a mac test environment (other than a virtualbox mac install, which I haven't bothered configuring for stomp), so no idea if it works or not, but seems like a low-enough-impact fix.
