### ISSUE TITLE
heartbeat_thread of HeartbeatListener, need to handle network error

### ISSUE THREAD

**Issue by Robert-Wang-sz** [jasonrbriggs/stomp.py#40]
Code:
---------------------------------------------
try:
   self.transport.transmit(utils.Frame(None, {}, None))
except exception.NotConnectedException:
   logger.Log.instance().debug("Lost connection, unable to send heartbeat")
-----------------------------------------------

need to fix as:

---------------------------------------------
try:
   self.transport.transmit(utils.Frame(None, {}, None))
except exception.NotConnectedException:
   logger.Log.instance().debug("Lost connection, unable to send heartbeat")
excep Exception:
    logger.Log.instance().debug("Error sending heartbeat frame")
-----------------------------------------------

**Comment by jasonrbriggs** [comment]
Sorry, but don't understand the difference.  Slight change to the error message doesn't make much difference in my opinion.

**Comment by estadtherr** [comment]
It looks like he wants a handler for "Exception" in addition to the handler for "NotConnectedException". I personally try to stay away from blanket catching of "Exception", since that will catch programming errors in addition to runtime errors, but that seems like the request.

**Comment by jasonrbriggs** [comment]
Ah. The bold bits kind-of caught me out.  Pretty obvious now you point it out.

Agreed in general, regarding catching Exception, but in this case it's the heartbeat loop.  Not 100% sure on reflection.  Don't like the idea of swallowing that sort of error, but not sure not-catching is the right answer either.  Will give it some further thought...

**Comment by jasonrbriggs** [comment]
Resolved in version 4.1.6
