### ISSUE TITLE
Release cadence

### ISSUE THREAD

**Issue by conbon** [jasonrbriggs/stomp.py#406]
Hello and thank you for your contribution to the community, along with all other contributors.

I am interested in an upcoming feature (websocket support) but would rather wait until an official release has been pushed to pypi.
I was just wondering about the release cadence of stomp.py - is there any proposed date of next release?

Thanks again!

@jasonrbriggs

**Comment by jasonrbriggs** [comment]
I've been holding off because I'm re-working the backend to try to use asyncio.  More painful to get going than expected, so it's caused a delay as a consequence.  However, I could just release 8.2.0 in the meantime and then roll out v9 when I get there...

**Comment by conbon** [comment]
Ahh, I see. 
I mean, obviously that would be great if you could but it's your time so only if it isn't much of a hassle.
If I can help with anything give me a shout!

**Comment by jasonrbriggs** [comment]
8.1.0 is released now...
