### ISSUE TITLE
8.1.0 tag missing on GitHub

### ISSUE THREAD

**Issue by sebix** [jasonrbriggs/stomp.py#415]
Version 8.1.0 is available in PyPI, but the repository has no corresponding tag

**Comment by sebix** [comment]
The commit is likely 6d965f87cc6678a8658ecf777894553211f49a06, but `pyproject.toml` says the version is 8.0.2. even in branch dev now:
https://github.com/jasonrbriggs/stomp.py/blob/7c32c768d5e7be4c667b4c34604cf376ee3bcafd/pyproject.toml#L3

**Comment by jasonrbriggs** [comment]
Fixed. Thanks.
