### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mattjgalloway** [jasonrbriggs/stomp.py#430]
Would it be possible to do a new release of stomp.py please?

I would like a release with this commit: https://github.com/jasonrbriggs/stomp.py/commit/7af96f725757cf0f4ba9ec7b6ff690e7316dfb66

But the latest, 8.1.0, does not have that (and some other commits that are in `dev` branch).

**Comment by jasonrbriggs** [comment]
8.1.1 is now released.
