### ISSUE TITLE
stomp.py 4.1.1 cannot be pip installed

### ISSUE THREAD

**Issue by alexpdp7** [jasonrbriggs/stomp.py#45]
$ mkvirtualenv scratch
New python executable in scratch/bin/python
Installing setuptools, pip...done.
(scratch)$ pip install stomp.py
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting stomp.py
  This repository located at xxxxxx is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host xxxxx'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Downloading stomp.py-4.1.1.tar.gz (134kB)
    100% |████████████████████████████████| 135kB 220kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-IV32I_/stomp.py/setup.py", line 4, in <module>
        import coverage
    ImportError: No module named coverage
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-IV32I_/stomp.py

**Comment by alexpdp7** [comment]
Ah, it seems that:

https://github.com/jasonrbriggs/stomp.py/pull/44

fixes this.

**Comment by jasonrbriggs** [comment]
Fixed now (I can pip install now at least).
