### ISSUE TITLE
\r should not be escaped with STOMP 1.1

### ISSUE THREAD

**Issue by scop** [jasonrbriggs/stomp.py#51]
Commit e527796664a09b26e77930208f685ec6e9250349 changes version 1.1 to escape \r, that's something that should be done only with 1.2, not 1.1. The 1.2 _escape_headers already does it for 1.2.

https://stomp.github.io/stomp-specification-1.1.html#Value_Encoding
https://stomp.github.io/stomp-specification-1.2.html#Value_Encoding

Also, the test cases added to the above commit puzzle me -- they add some \n's to the test cases but the actual change deals with \r...?

**Comment by jasonrbriggs** [comment]
Trying to fix something else and added by mistake.  Removed and then re-implemented the change properly.
