### ISSUE TITLE
improve documentation

### ISSUE THREAD

**Issue by dpk** [jasonrbriggs/stomp.py#54]
API docs are confusingly organized and the "simple example" is laughably *over*simplified.

**Comment by jasonrbriggs** [comment]
API docs are generated by doxygen... not sure there's a lot that can be done with the structure there.

**Comment by dpk** [comment]
Right, and that is half the problem. It explains nothing but the internal structure of the modules and classes. How to actually do anything with the library is obscure.

Please see for example [Whoosh](http://pythonhosted.org/Whoosh/) as an example of how to do great documentation. Full walkthrough of implementing things, plus an API reference which actually explains what each method does, and how each argument to each method affects it.

**Comment by rgazaryants** [comment]
Unfortunately, you gotta read the source to figure out what's what - maybe.

**Comment by dpk** [comment]
I tried that. I couldn’t figure out what was what.

**Comment by jasonrbriggs** [comment]
Initial version of new [docs](http://jasonrbriggs.github.io/stomp.py/index.html) uploaded.  Closing this for the moment.
