### ISSUE TITLE
timeout not working on Transport.start 

### ISSUE THREAD

**Issue by farzadanooshah** [jasonrbriggs/stomp.py#55]
Hi,

I recently noticed that the timeout, set at the time of initializing stomp.Connection(), wouldn't work properly on start method. 
For e.g. If I enter the rabbitmq host address to an unreachable address, it takes about a minute to get the exception of type stomp.exception.ConnectFailedException even though I set the timeout to 10.

I just checked the source code and following change seems to solve the issue:
Line 696 of file stomp/transport.py, the code "self.socket.settimeout(self.__timeout)" is probably inside "if need_ssl: " block by mistake and just taking the code out of "if need_ssl" block would solve the issue.

Regards

**Comment by jasonrbriggs** [comment]
Fixed in the next release.
