### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by will835559313** [jasonrbriggs/stomp.py#58]
when I run this example that from https://github.com/jasonrbriggs/stomp.py/wiki/Simple-Example,I got that error

python 2.6.6
latest stomp.py version

**Comment by jasonrbriggs** [comment]
I don't have python2.6.6 installed, but I don't see the problem with 2.7, I'm afraid...

```
$ python -V
Python 2.7.9
$ pip install stomp.py
Collecting stomp.py
  Using cached stomp.py-4.1.5.tar.gz
Building wheels for collected packages: stomp.py
  Running setup.py bdist_wheel for stomp.py
  Stored in directory: /home/jasonbriggs/.cache/pip/wheels/50/9d/d7/81ae86f351418e171732f0ceabba3e0eacb681658
Successfully built stomp.py
Installing collected packages: stomp.py
Successfully installed stomp.py-4.1.5
$ python test.py hello there
received a message "hello there"
```

**Comment by tbennett6421** [comment]
Sorry to necro, you will get this error if you're trying to run a file named stomp.py and using `import stomp`

Navigate to `C:\` or `/tmp/` and the following should work
```python
>>> import stomp
>>> conn = stomp.Connection()
```
Hope that helps anyone who stumbles upon this issue
