### ISSUE TITLE
Bug in setting keepalive settings on socket

### ISSUE THREAD

**Issue by choudhary001** [jasonrbriggs/stomp.py#60]
In transport.py in method __enable_keepalive, If keepalive settings are passed they are *not* applied to the actual socket.

        ka = self.__keepalive

        if not ka: 
            return

        if ka: 
            ka_sig = 'auto'
            ka_args = ()
        else:
            try:
                ka_sig = ka[0]
                ka_args = ka[1:]
            except Exception:
                log.error("keepalive: bad specification %r", ka) 
                return                            

The code in else block never gets executed as ka will always be defined when it reaches the if condition.
It used to work in stomp.py v3.1.1 because of this code:

        ka = self.__keepalive

        if not ka: 
            return

        # The if condition fails as ka is a tuple and we are able to override socket settings
        if ka == True:
            ka_sig = 'auto'
            ka_args = ()
        else:
            try:
                ka_sig = ka[0]
                ka_args = ka[1:]
            except Exception:
                log.error('keepalive: bad specification %r' % (ka,))
                return

Please take a look and patch it as early as possible?

**Comment by rgbyrnes** [comment]
It looks like this was broken by https://github.com/jasonrbriggs/stomp.py/commit/055640fe773876d6bc313ec321c0cad8dfdee010, which didn't realize that the keepalive parameter can be specified as either a boolean or tuple.

**Comment by jasonrbriggs** [comment]
Fixed in 4.1.7
