### ISSUE TITLE
ERROR:stomp.py:Lost connection

### ISSUE THREAD

**Issue by xinghailong** [jasonrbriggs/stomp.py#63]
Recently there have been many such mistakes, can you provide some of the ideas to solve it?

v3.1.1

activeMQ
![image](https://cloud.githubusercontent.com/assets/7324577/11646860/f89d8f18-9d9c-11e5-8873-88b3a73dfb44.png)

**Comment by xinghailong** [comment]
![image](https://cloud.githubusercontent.com/assets/7324577/11646856/e839678c-9d9c-11e5-8d95-80cf9f23f1f5.png)

**Comment by jasonrbriggs** [comment]
I'm afraid you haven't given enough info to be able to diagnose the problem.  Suggest you check the activemq logs for any error messages.
