### ISSUE TITLE
Logging suggestion

### ISSUE THREAD

**Issue by choudhary001** [jasonrbriggs/stomp.py#65]
Below code in transport.py module gives out warning for every failed connection attempt in the given host:port list.

```python
except socket.error:
      self.socket = None
      connect_count += 1
      log.warning("Could not connect to host %s, port %s", host_and_port[0], host_and_port[1], exc_info=1)
```
My suggestion is to make the log statement in the above code to be logged at INFO level and give out a warning only if we fail to connect to any of the host:port pairs provided in the list.

The reason I am suggesting this is that default log level in python WARN and if the client is able to connect to one of the host:port pair in the list, It should be considered a success without any abnormalities and more often than not the warning produced by this code has caused confusions to the people not much familiar with the API.
Now, I know there are ways to suppress this log statement in the client code but they are cumbersome and making the log statement at INFO level seems like reasonable logging improvement and we can anyway log a WARNING or ERROR if we fail to connect any of host:port pair in this list.

Cheers,
Abhishek

**Comment by jasonrbriggs** [comment]
Change to info is fine - don't think there's a need for a further warn message - an exception is raised if the connection fails anyway. Will change in the next release.
