### ISSUE TITLE
(windows only?) message sent right before interpreter exit is never received

### ISSUE THREAD

**Issue by dtenenba** [jasonrbriggs/stomp.py#70]
Hi,

With an ActiveMQ broker running on a machine called `broker` (not sure if it matters what kind of broker is running) and the following listener (`test_listener.py`) running:

```
import stomp
import time
stompClient = stomp.Connection([("broker", 61613)])
class MyListener(stomp.ConnectionListener):
   def on_error(self, headers, message):
       print('received an error "%s"' % message)
   def on_message(self, headers, message):
       print('received a message "%s"' % message)
stompClient.set_listener('', MyListener())
stompClient.start()
stompClient.connect()
stompClient.subscribe(destination='/topic/test_autoexit', id=1, ack='auto')

while True:
    time.sleep(0.2)
```

When the following script (`test_sender.py`), is run on Windows (server 2008 R2 Enterprise SP1 with ActiveState python 2.7.1) the message it sends is never received by the listener. It works fine on linux (Ubuntu 14.04.3 LTS, python 2.7.6). Both machines are running stomp.py 4.1.8.

```
import stomp
import time

stompClient = stomp.Connection([("broker", 61613)])
stompClient.start()
stompClient.connect()

stompClient.send(body="foo", destination="/topic/test_autoexit")
#print("about to sleep")
#time.sleep(1)
```

If I uncomment the last two lines (thereby sleeping for one second after sending) and run it again, the message is received by the listener. The results are consistent.
So it has something to do (as far as I can tell) with exiting the interpreter right after calling `send()`.
Sleeping for 0.1 seconds seems to be enough to ensure the message is sent, but sleeping for 0.01 seconds is not long enough.

Thanks.

**Comment by jasonrbriggs** [comment]
Unfortunately I can't reproduce it. I don't have a "real" windows machine -- just win7 running inside virtual box, and I consistently *don't* get the problem.  I've tried with both the latest ActiveState python 2.7, and with the default Python 2.7 installation, and the message always arrives.  So whether it's an issue with win server 2008, a problem with the version of ActiveState python you're using, or a combination of the two... not entirely sure. Any possibility you could re-test it with a different message broker perhaps (to eliminate that also being part of the problem).

**Comment by dtenenba** [comment]
I set up a rabbitmq broker with username guest and password guest. 

I modified the listener to connect with this broker on the appropriate machine and to use the right credentials but it gives me:

```
received an error "non-loopback access denied"
received an error "You must log in using CONNECT first"
```

(The script continues here, going into its sleep loop, but does not appear to receive messages, even those sent from a linux machine.)

Not sure what the problem is. I call `stompClient.start()` first before calling `stompClient.connect()` which could explain the second error, but if I swap the two lines, I get a `stomp.exception.NotConnectedException`. 

Any ideas? I would like to test this with another broker to eliminate that as the problem.

**Comment by jasonrbriggs** [comment]
Did you enable the stomp plugin?

```rabbitmq-plugins enable rabbitmq_stomp```

And have you tried connecting with:

```python
stompClient.start()
stompClient.connect('guest', 'guest', wait=True)
```

**Comment by dtenenba** [comment]
Yes, the stomp plugin is enabled. I can telnet to port 61613 (I'm using a docker container from https://github.com/pavlo/docker-rabbitmq-stomp ). 

I tried adding the wait=True parameter and now get this:

```
No handlers could be found for logger "stomp.py"
Traceback (most recent call last):
  File "listener.py", line 9, in <module>
    stompClient.start()
  File "/home/biocadmin/spb_history/env/local/lib/python2.7/site-packages/stomp/connect.py", line 32, in start
    self.transport.start()
  File "/home/biocadmin/spb_history/env/local/lib/python2.7/site-packages/stomp/transport.py", line 107, in start
    self.attempt_connection()
  File "/home/biocadmin/spb_history/env/local/lib/python2.7/site-packages/stomp/transport.py", line 721, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
```

The full listener script at this point is:

```
import stomp
import time
stompClient = stomp.Connection([("taipan", 61613)])
class MyListener(stomp.ConnectionListener):
   def on_error(self, headers, message):
       print('received an error "%s"' % message)
   def on_message(self, headers, message):
       print('received a message "%s"' % message)
stompClient.start()
stompClient.connect('guest', 'guest', wait=True)
stompClient.set_listener('', MyListener())
stompClient.subscribe(destination='/topic/test_autoexit', id=1, ack='auto')

while True:
    time.sleep(0.2)
```

**Comment by jasonrbriggs** [comment]
That error is thrown if it's unable to make a socket connection to the specified host.  Rather than "taipan" can you try the ipaddress? (Don't know why it would make any difference since you can telnet to it, but worth a go).

PS. I took your code, modified the host to my test server running rabbitmq, and it worked fine.

**Comment by jasonrbriggs** [comment]
Actually if I run your code without changing the hostname, I get the same error.  So definitely seems like 'taipan' isn't accessible...

**Comment by dtenenba** [comment]
Duh. I was running the listener outside of the network where taipan exists (and it's not accessible over the internet). Sorry, my bad. Will fix this situation and update you.

**Comment by dtenenba** [comment]
OK, I should not have used 'guest' as the user name, that user can only access on the loopback interface.

I changed the rabbitmq server to use 'admin/admin' as the credentials. And I changed the listener and sender accordingly. 

I can send the message from windows and it is received but the sender on windows exits with

```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
```

Looks like maybe there is supposed to be a stack trace after that but that's all I see.
So this seems like it's still a problem, as the error is unexpected although the message sending works.

**Comment by dtenenba** [comment]
Incidentally, if I uncomment the sleep line in the sender, the error goes away. 

So, to summarize:

With activemq:

listener never receives message unless there is a sleep after sending it

With rabbitmq:

listener receives message no matter what, but if there is no sleep after sending it there is an "Exception in thread".

**Comment by jasonrbriggs** [comment]
The error might be thrown due to the fact that there's a receiver loop in a separate thread which isn't actually shutdown (in your code). If you add a disconnect that might go away:

```python
conn.disconnect(receipt=None)
```

It does seem like the original problem is some combination of ActiveMQ and Windows... not a clue why (actually can you double-check whether disconnecting also helps with the original problem as well?)

**Comment by dtenenba** [comment]
Yes, that does the trick. Thanks!
