### ISSUE TITLE
How can I specify a protocol?

### ISSUE THREAD

**Issue by GildedHonour** [jasonrbriggs/stomp.py#92]
How can I specify a protocol? I need "ssl+stomp" or just "ssl" or "https" or "amqp+ssl".

This doesn't work:

```
conn = stomp.Connection(host_and_ports=[("stomp+ssl://something.com", 61613)], use_ssl=True)
```

and even this doesn't:

```
conn = stomp.Connection(host_and_ports=[("ssl://something.com", 61613)], use_ssl=True)
```

whereas this does but it costed me a few hours to discover it because in the documentation isn't described:

```
conn = stomp.Connection(host_and_ports=[("something.com", 61613)], use_ssl=True)
```

**Comment by jasonrbriggs** [comment]
Sorry for the delay replying.  It's "hosts and ports" not "urn and ports". So you don't specify the protocol, you specify the domain/ip and port (as per http://jasonrbriggs.github.io/stomp.py/api.html#establishing-a-connection).  Under the covers this is a low level socket connection.
