### ISSUE TITLE
ssl example

### ISSUE THREAD

**Issue by michaelbini** [jasonrbriggs/stomp.py#96]
Hi,
Can you please post an example on how to create sender with SSL certificate.
 Here is how I send message:

`import time
import sys
import stomp
conn = stomp.Connection()
conn.start()
conn.connect()

conn.send(body='Hello world', destination='/queue/test')
conn.disconnect()`
How do I add my cer and key to the message?
Thanks

**Comment by zachjacobs** [comment]
We have gotten this to work but it's rather tricky, can you try:
`
ssl_result = conn.set_ssl(for_hosts=[(<ipaddress>,<port>)],key_file="***.key",cert_file="***.cert")
`
beforeconn.start()

**Comment by michaelbini** [comment]
Thanks for the replay, 
I will try it on Sunday, and update here the result, but how do I provide the password for the key and cert ?

**Comment by cjdcordeiro** [comment]
hi guys,

quick question:
are these examples compatible with older releases (4.1.11 and 4.1.9)?
For me both this, the ssl_test.py and the most basic of all, the "Simple Example", fail with stomp.exception.ConnectFailedException

and I've tried in 3 different machines already with 3 different stomp versions

Cheers

**Comment by jasonrbriggs** [comment]
The set_ssl signature has been the same since (at least) 4.1.9, so the examples should still work -- and are tested regularly so working for me.

**Comment by Kristin0** [comment]
@jasonrbriggs i get an issue "Exception: SSL connection requested, but SSL library not found"
trying to do     
`
conn.set_ssl(for_hosts=[("54.175.111.16",61614)],key_file="test.key",cert_file="test.cert")
`
in image openssl is already the newest version (1.1.1n-0+deb10u3).

**Comment by RobertoTorta97** [comment]
> @jasonrbriggs i get an issue "Exception: SSL connection requested, but SSL library not found" trying to do `conn.set_ssl(for_hosts=[("54.175.111.16",61614)],key_file="test.key",cert_file="test.cert")` in image openssl is already the newest version (1.1.1n-0+deb10u3).

I have the same error, did you manage to solve it?
